import { jest } from "@jest/globals";
import { render, screen } from "@testing-library/react";
import React from "react";

const mockQbrList = jest.fn();
const mockGetApprovedMembership = jest.fn().mockResolvedValue({ organization_id: "org-1" });

jest.mock("next/link", () => ({
  __esModule: true,
  default: ({ children, href, ...props }: Record<string, unknown>) =>
    React.createElement("a", { href, ...props }, children as React.ReactNode),
}));

jest.mock("@/lib/api", () => ({
  getApiClient: jest.fn().mockReturnValue({
    qbr: { list: mockQbrList },
  }),
}));

jest.mock("@/lib/auth/membership", () => ({
  getApprovedMembership: mockGetApprovedMembership,
}));

jest.mock("@/components/Breadcrumbs", () => ({
  __esModule: true,
  default: () => React.createElement("nav", { "aria-label": "Breadcrumb" }),
}));

jest.mock("@/components/portal/PortalSubnav", () => ({
  __esModule: true,
  default: () => React.createElement("nav", null),
}));

describe("PortalQbrPage", () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockGetApprovedMembership.mockResolvedValue({ organization_id: "org-1" });
  });

  it("renders heading", async () => {
    mockQbrList.mockResolvedValue({ items: [] });

    const { default: Page } = await import("@/app/(portal)/portal/qbr/page");
    const element = await Page();
    render(element);

    expect(screen.getByRole("heading", { name: /qbr reports/i })).toBeInTheDocument();
  });

  it("renders breadcrumbs", async () => {
    mockQbrList.mockResolvedValue({ items: [] });

    const { default: Page } = await import("@/app/(portal)/portal/qbr/page");
    const element = await Page();
    render(element);

    expect(screen.getAllByRole("navigation").length).toBeGreaterThanOrEqual(1);
  });

  it("renders reports when data exists", async () => {
    mockQbrList.mockResolvedValue({
      items: [
        {
          id: "r1",
          title: "Q1 2026 Review",
          status: "published",
          period_start: "2026-01-01T00:00:00Z",
          period_end: "2026-03-31T00:00:00Z",
          generated_by: "Jane Smith",
          created_at: "2026-04-01T00:00:00Z",
        },
        {
          id: "r2",
          title: "Q2 2026 Draft",
          status: "draft",
          period_start: "2026-04-01T00:00:00Z",
          period_end: "2026-06-30T00:00:00Z",
          generated_by: "John Doe",
          created_at: "2026-07-01T00:00:00Z",
        },
      ],
    });

    const { default: Page } = await import("@/app/(portal)/portal/qbr/page");
    const element = await Page();
    render(element);

    expect(screen.getByText("Q1 2026 Review")).toBeInTheDocument();
    expect(screen.getByText("Q2 2026 Draft")).toBeInTheDocument();
    expect(screen.getByText("Published")).toBeInTheDocument();
    expect(screen.getByText("Draft")).toBeInTheDocument();
    expect(screen.getByText(/Generated by: Jane Smith/)).toBeInTheDocument();
    expect(screen.getByText(/Generated by: John Doe/)).toBeInTheDocument();
  });

  it("shows empty state", async () => {
    mockQbrList.mockResolvedValue({ items: [] });

    const { default: Page } = await import("@/app/(portal)/portal/qbr/page");
    const element = await Page();
    render(element);

    expect(screen.getByText("No QBR reports found.")).toBeInTheDocument();
  });

  it("shows access restricted when no org", async () => {
    mockGetApprovedMembership.mockResolvedValue(null);

    const { default: Page } = await import("@/app/(portal)/portal/qbr/page");
    const element = await Page();

    expect(element).toBeNull();
  });

  it("shows report count", async () => {
    mockQbrList.mockResolvedValue({
      items: [
        {
          id: "r1",
          title: "Q1 Review",
          status: "published",
          created_at: new Date().toISOString(),
          generated_by: "Admin",
        },
      ],
    });

    const { default: Page } = await import("@/app/(portal)/portal/qbr/page");
    const element = await Page();
    render(element);

    expect(screen.getByText(/1 reports for your organization/)).toBeInTheDocument();
  });
});
