version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      sentry:
        patterns:
          - "@sentry/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
          - "supertest"
          - "@types/supertest"
          - "@testing-library/*"
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
