import { getApiClient } from "@/lib/api";
import { requireAdminAccess } from "@/lib/auth/admin";
import { notFound } from "next/navigation";
import Link from "next/link";
import Breadcrumbs from "@/components/Breadcrumbs";
import AdminSubnav from "@/components/admin/AdminSubnav";
import AdminPageShell from "@/components/admin/AdminPageShell";

export const dynamic = "force-dynamic";
export const metadata = { title: "QBR Report - Admin - Maine CyberTech" };

function fmtCurrency(n: number): string {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);
}

function renderValue(value: unknown): string {
  if (value === null || value === undefined) return "—";
  if (typeof value === "number") return Number.isInteger(value) ? String(value) : String(value);
  if (typeof value === "object") {
    try {
      return JSON.stringify(value);
    } catch {
      return "—";
    }
  }
  return String(value);
}

export default async function QbrDetailPage(props: { params: Promise<{ id: string }> }) {
  await requireAdminAccess();
  const { id } = await props.params;
  const api = getApiClient();

  let report: any = null;
  try {
    report = await api.qbr.get(id);
  } catch {
    notFound();
  }
  if (!report) notFound();

  const reportData = report.report_data ?? {};
  const sections = Object.entries(reportData).filter(([, v]) => v !== null && v !== undefined);

  return (
    <AdminPageShell
      breadcrumbs={
        <Breadcrumbs
          items={[
            { label: "Admin", href: "/admin" },
            { label: "QBR Reports", href: "/admin/qbr" },
            { label: report.title ?? "Report" },
          ]}
        />
      }
      subnav={<AdminSubnav current="qbr" />}
      title={report.title ?? "QBR Report"}
      description={
        report.period_start
          ? `${String(report.period_start).slice(0, 10)} → ${String(report.period_end ?? "").slice(0, 10)}`
          : undefined
      }
      actions={
        <Link href="/admin/qbr" className="cyber-button-secondary">
          Back
        </Link>
      }
    >
      <div className="space-y-6">
        {report.summary && (
          <section className="cyber-panel">
            <h2 className="cyber-heading text-lg">Summary</h2>
            <p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-slate-300">
              {report.summary}
            </p>
          </section>
        )}

        {sections.length > 0 ? (
          sections.map(([key, value]) => (
            <section key={key} className="cyber-panel">
              <h2 className="cyber-heading text-lg capitalize">{key.replace(/_/g, " ")}</h2>
              {Array.isArray(value) ? (
                <ul className="mt-3 space-y-1.5">
                  {value.map((item: unknown, i: number) => (
                    <li key={i} className="text-sm text-slate-300">
                      {typeof item === "object" && item !== null ? (
                        <pre className="whitespace-pre-wrap rounded-md bg-cyber-base p-3 text-xs text-slate-300">
                          {JSON.stringify(item, null, 2)}
                        </pre>
                      ) : (
                        renderValue(item)
                      )}
                    </li>
                  ))}
                </ul>
              ) : typeof value === "object" ? (
                <dl className="mt-3 grid gap-2 sm:grid-cols-2">
                  {Object.entries(value as Record<string, unknown>).map(([k, v]) => (
                    <div key={k} className="rounded-md bg-cyber-base/60 p-3">
                      <dt className="text-[11px] uppercase tracking-widest text-slate-500">
                        {k.replace(/_/g, " ")}
                      </dt>
                      <dd className="mt-1 text-sm text-slate-200">
                        {typeof v === "number" && /cost|price|amount|total|savings/i.test(k)
                          ? fmtCurrency(v)
                          : renderValue(v)}
                      </dd>
                    </div>
                  ))}
                </dl>
              ) : (
                <p className="mt-3 text-sm text-slate-300">{renderValue(value)}</p>
              )}
            </section>
          ))
        ) : (
          <p className="rounded-lg border border-white/10 bg-cyber-base/60 p-4 text-sm text-slate-400">
            No aggregated data for this report yet.
          </p>
        )}

        <section className="cyber-panel">
          <div className="flex flex-wrap gap-2">
            <span className="cyber-pill">Status: {report.status}</span>
            <span className="cyber-pill">Visibility: {report.visibility}</span>
            {report.generated_by && (
              <span className="cyber-pill">Generated by {report.generated_by}</span>
            )}
          </div>
        </section>
      </div>
    </AdminPageShell>
  );
}
