import Link from "next/link";
import { getApiClient } from "@/lib/api";
import { getApprovedMembership } from "@/lib/auth/membership";
import Breadcrumbs from "@/components/Breadcrumbs";
import EmptyState from "@/components/EmptyState";
import StatusPill from "@/components/StatusPill";
import PortalSubnav from "@/components/portal/PortalSubnav";

import DataErrorNote from "@/components/admin/DataErrorNote";
import { formatDate } from "@/lib/format";
export const dynamic = "force-dynamic";
export const metadata = { title: "QBR Reports - Portal - Maine CyberTech" };

export default async function PortalQbrPage() {
  const membership = await getApprovedMembership();
  if (!membership) return null;
  let loadFailed = false;
  const api = getApiClient();
  const orgId = membership.organization_id as string;
  let items: Array<Record<string, unknown>> = [];
  try {
    const r = await api.qbr.list({ organizationId: orgId });
    items = r.items as unknown as typeof items;
  } catch (error) {
    console.error("[qbr/page]", error);
    loadFailed = true;
  }

  function statusLabel(status: string) {
    const s = status.toLowerCase();
    if (s === "published") return "Published";
    if (s === "draft") return "Draft";
    return status;
  }

  return (
    <div className="space-y-6" role="region" aria-label="QBR Reports">
      <Breadcrumbs
        items={[{ label: "Portal", href: "/portal/dashboard" }, { label: "QBR Reports" }]}
      />
      <PortalSubnav current="qbr" />
      {loadFailed ? <DataErrorNote what="qbr" /> : null}
      <h1 className="text-2xl font-semibold text-slate-50">QBR Reports</h1>
      <p className="text-sm text-slate-400">{items.length} reports for your organization.</p>
      <div className="space-y-3">
        {items.map((item) => (
          <div
            key={String(item.id)}
            className="rounded-lg border border-white/10 bg-cyber-base/60 p-4"
          >
            <div className="flex items-start justify-between">
              <div>
                <p className="font-medium text-slate-50">{String(item.title)}</p>
                <p className="mt-1 text-xs text-slate-400">
                  Period: {item.period_start ? formatDate(item.period_start) : "—"}
                  {" — "}
                  {item.period_end ? formatDate(item.period_end) : "—"}
                </p>
                <p className="mt-1 text-xs text-slate-400">
                  Generated by: {item.generated_by ? String(item.generated_by) : "—"}
                </p>
                <p className="mt-1 text-xs text-slate-400">
                  Created: {formatDate(item.created_at)}
                </p>
              </div>
              <StatusPill status={statusLabel(String(item.status))} />
            </div>
          </div>
        ))}
        {!loadFailed && items.length === 0 && (
          <EmptyState icon="📊" title="No QBR reports found." />
        )}
      </div>
      <Link href="/portal/dashboard" className="text-sm text-emerald-500 hover:text-emerald-400">
        &larr; Dashboard
      </Link>
    </div>
  );
}
