import Link from "next/link";
import { getApiClient } from "@/lib/api";
import { getApprovedMembership } from "@/lib/auth/membership";
import Breadcrumbs from "@/components/Breadcrumbs";
import PortalSubnav from "@/components/portal/PortalSubnav";

export const dynamic = "force-dynamic";
export const metadata = { title: "QBR Reports - Portal - Maine CyberTech" };

export default async function PortalQbrPage() {
  const membership = await getApprovedMembership();
  if (!membership) return null;
  const api = getApiClient();
  const orgId = membership.organization_id as string;
  let items: Array<Record<string, unknown>> = [];
  try {
    const r = await api.qbr.list({ organizationId: orgId });
    items = r.items as unknown as typeof items;
  } catch {}

  function statusBadge(status: string) {
    const s = status.toLowerCase();
    if (s === "published")
      return (
        <span className="rounded-full bg-emerald-500/20 px-2 py-0.5 text-xs text-emerald-400">
          Published
        </span>
      );
    if (s === "draft")
      return (
        <span className="rounded-full bg-amber-500/20 px-2 py-0.5 text-xs text-amber-400">
          Draft
        </span>
      );
    return (
      <span className="rounded-full bg-slate-500/20 px-2 py-0.5 text-xs text-slate-400">
        {status}
      </span>
    );
  }

  return (
    <div className="space-y-6" role="region" aria-label="QBR Reports">
      <Breadcrumbs
        items={[{ label: "Portal", href: "/portal/dashboard" }, { label: "QBR Reports" }]}
      />
      <PortalSubnav current="qbr" />
      <h1 className="text-2xl font-semibold text-slate-50">QBR Reports</h1>
      <p className="text-sm text-slate-400">{items.length} reports for your organization.</p>
      <div className="space-y-3">
        {items.map((item) => (
          <div
            key={String(item.id)}
            className="rounded-lg border border-white/10 bg-[#0A1118]/60 p-4"
          >
            <div className="flex items-start justify-between">
              <div>
                <p className="font-medium text-slate-50">{String(item.title)}</p>
                <p className="mt-1 text-xs text-slate-400">
                  Period:{" "}
                  {item.period_start
                    ? new Date(String(item.period_start)).toISOString().slice(0, 10)
                    : "—"}
                  {" — "}
                  {item.period_end
                    ? new Date(String(item.period_end)).toISOString().slice(0, 10)
                    : "—"}
                </p>
                <p className="mt-1 text-xs text-slate-400">
                  Generated by: {item.generated_by ? String(item.generated_by) : "—"}
                </p>
                <p className="mt-1 text-xs text-slate-400">
                  Created: {new Date(String(item.created_at)).toISOString().slice(0, 10)}
                </p>
              </div>
              {statusBadge(String(item.status))}
            </div>
          </div>
        ))}
        {items.length === 0 && <p className="text-sm text-slate-400">No QBR reports found.</p>}
      </div>
      <Link href="/portal/dashboard" className="text-sm text-emerald-500 hover:text-emerald-400">
        &larr; Dashboard
      </Link>
    </div>
  );
}
