import { buildPaths, type RouteDef, pathParam, queryParam } from "./builder";

const auth: RouteDef[] = [
  {
    method: "post",
    path: "/auth/sign-in",
    summary: "Sign in with email/password",
    tag: "Auth",
    auth: false,
    body: {
      type: "object",
      properties: { email: { type: "string" }, password: { type: "string" } },
      required: ["email", "password"],
    },
  },
  {
    method: "post",
    path: "/auth/sign-up",
    summary: "Create account",
    tag: "Auth",
    auth: false,
    body: {
      type: "object",
      properties: {
        email: { type: "string" },
        password: { type: "string" },
        fullName: { type: "string" },
      },
      required: ["email", "password"],
    },
  },
  { method: "post", path: "/auth/sign-out", summary: "Sign out", tag: "Auth", auth: false },
  { method: "get", path: "/auth/me", summary: "Get current user", tag: "Auth" },
  {
    method: "post",
    path: "/auth/callback",
    summary: "Exchange auth code for session",
    tag: "Auth",
    auth: false,
  },
  {
    method: "post",
    path: "/auth/forgot-password",
    summary: "Request password reset email",
    tag: "Auth",
    auth: false,
    body: { type: "object", properties: { email: { type: "string" } }, required: ["email"] },
  },
  {
    method: "post",
    path: "/auth/reset-password",
    summary: "Reset password with token",
    tag: "Auth",
    auth: false,
    body: {
      type: "object",
      properties: { token: { type: "string" }, password: { type: "string" } },
      required: ["token", "password"],
    },
  },
];

const auth2: RouteDef[] = [
  { method: "get", path: "/profiles", summary: "List profiles", tag: "Profiles" },
  {
    method: "patch",
    path: "/profiles/{id}",
    summary: "Update profile",
    tag: "Profiles",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/profiles/{id}/avatar",
    summary: "Upload avatar",
    tag: "Profiles",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/me/permissions",
    summary: "Get my effective permissions",
    tag: "Permissions",
  },
  { method: "get", path: "/organizations", summary: "List organizations", tag: "Organizations" },
  { method: "post", path: "/organizations", summary: "Create organization", tag: "Organizations" },
  {
    method: "get",
    path: "/organizations/{id}",
    summary: "Get organization",
    tag: "Organizations",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/organizations/{id}",
    summary: "Update organization",
    tag: "Organizations",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/organizations/{id}",
    summary: "Delete organization",
    tag: "Organizations",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/organizations/{id}/detail",
    summary: "Get organization detail (compound)",
    tag: "Organizations",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/organizations/{id}/logo",
    summary: "Upload organization logo",
    tag: "Organizations",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/organizations/{id}/domains",
    summary: "List organization domains",
    tag: "Organizations",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/organizations/{id}/domains",
    summary: "Add domain",
    tag: "Organizations",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/organizations/{id}/domains/{domainId}",
    summary: "Verify domain",
    tag: "Organizations",
    params: [pathParam("id"), pathParam("domainId")],
  },
  {
    method: "delete",
    path: "/organizations/{id}/domains/{domainId}",
    summary: "Remove domain",
    tag: "Organizations",
    params: [pathParam("id"), pathParam("domainId")],
  },
  { method: "get", path: "/memberships", summary: "List memberships", tag: "Memberships" },
  { method: "get", path: "/memberships/mine", summary: "Get my memberships", tag: "Memberships" },
  {
    method: "post",
    path: "/memberships/invite",
    summary: "Invite user to org",
    tag: "Memberships",
  },
  {
    method: "patch",
    path: "/memberships/{id}",
    summary: "Update membership status",
    tag: "Memberships",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/memberships/{id}",
    summary: "Remove membership",
    tag: "Memberships",
    params: [pathParam("id")],
  },
  { method: "get", path: "/users", summary: "List users", tag: "Users" },
  {
    method: "get",
    path: "/users/{id}",
    summary: "Get user",
    tag: "Users",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/users/{id}/detail",
    summary: "Get user with memberships (compound)",
    tag: "Users",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/users/{id}/role",
    summary: "Update user role",
    tag: "Users",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/users/{id}/permissions",
    summary: "Get user permissions",
    tag: "Users",
    params: [pathParam("id")],
  },
  {
    method: "put",
    path: "/users/{id}/permissions",
    summary: "Update user permission overrides",
    tag: "Users",
    params: [pathParam("id")],
  },
  { method: "get", path: "/roles", summary: "List roles", tag: "Roles" },
  {
    method: "get",
    path: "/roles/with-permissions",
    summary: "List roles with permission counts",
    tag: "Roles",
  },
  { method: "post", path: "/roles", summary: "Create role", tag: "Roles" },
  {
    method: "get",
    path: "/roles/{id}",
    summary: "Get role",
    tag: "Roles",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/roles/{id}",
    summary: "Update role",
    tag: "Roles",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/roles/{id}",
    summary: "Delete role",
    tag: "Roles",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/roles/{id}/permissions",
    summary: "List role permissions",
    tag: "Roles",
    params: [pathParam("id")],
  },
  {
    method: "put",
    path: "/roles/{id}/permissions",
    summary: "Update role permissions",
    tag: "Roles",
    params: [pathParam("id")],
  },
];

const ticketsProjects: RouteDef[] = [
  {
    method: "get",
    path: "/tickets",
    summary: "List tickets",
    tag: "Tickets",
    params: [queryParam("status"), queryParam("priority"), queryParam("page"), queryParam("limit")],
  },
  { method: "post", path: "/tickets", summary: "Create ticket", tag: "Tickets" },
  { method: "post", path: "/tickets/bulk", summary: "Bulk update tickets", tag: "Tickets" },
  {
    method: "get",
    path: "/tickets/export",
    summary: "Export tickets (CSV/JSON)",
    tag: "Tickets",
    params: [queryParam("format"), queryParam("status")],
  },
  {
    method: "get",
    path: "/tickets/{id}",
    summary: "Get ticket",
    tag: "Tickets",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/tickets/{id}",
    summary: "Update ticket",
    tag: "Tickets",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/tickets/{id}",
    summary: "Delete ticket",
    tag: "Tickets",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/tickets/{id}/comments",
    summary: "List ticket comments",
    tag: "Tickets",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/tickets/{id}/comments",
    summary: "Add ticket comment",
    tag: "Tickets",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/tickets/{id}/comments/{commentId}",
    summary: "Edit ticket comment",
    tag: "Tickets",
    params: [pathParam("id"), pathParam("commentId")],
  },
  {
    method: "get",
    path: "/projects",
    summary: "List projects",
    tag: "Projects",
    params: [queryParam("status"), queryParam("page"), queryParam("limit")],
  },
  { method: "post", path: "/projects", summary: "Create project", tag: "Projects" },
  {
    method: "get",
    path: "/projects/export",
    summary: "Export projects (CSV/JSON)",
    tag: "Projects",
    params: [queryParam("format")],
  },
  {
    method: "get",
    path: "/projects/{id}",
    summary: "Get project",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/projects/{id}",
    summary: "Update project",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/projects/{id}",
    summary: "Delete project",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/projects/{id}/detail",
    summary: "Get project detail (compound)",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/projects/{id}/tasks",
    summary: "List project tasks",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/projects/{id}/tasks",
    summary: "Create project task",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/projects/{id}/tasks/{taskId}",
    summary: "Update task",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId")],
  },
  {
    method: "delete",
    path: "/projects/{id}/tasks/{taskId}",
    summary: "Delete task",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId")],
  },
  {
    method: "get",
    path: "/projects/{id}/tasks/{taskId}/comments",
    summary: "List task comments",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId")],
  },
  {
    method: "post",
    path: "/projects/{id}/tasks/{taskId}/comments",
    summary: "Add task comment",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId")],
  },
  {
    method: "patch",
    path: "/projects/{id}/tasks/{taskId}/comments/{commentId}",
    summary: "Edit task comment",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId"), pathParam("commentId")],
  },
  {
    method: "get",
    path: "/projects/{id}/tasks/comments",
    summary: "List all task comments",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/projects/{id}/tasks/read-states",
    summary: "Get task read states",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/projects/{id}/tasks/reorder",
    summary: "Reorder tasks",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/projects/{id}/tasks/{taskId}/read",
    summary: "Mark task read",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId")],
  },
  {
    method: "post",
    path: "/projects/{id}/tasks/{taskId}/approve",
    summary: "Approve task",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId")],
  },
  {
    method: "post",
    path: "/projects/{id}/tasks/{taskId}/portal-comment",
    summary: "Add portal comment to task",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId")],
  },
  {
    method: "get",
    path: "/projects/{id}/updates",
    summary: "List project updates",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/projects/{id}/updates",
    summary: "Create project update",
    tag: "Projects",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/projects/{id}/updates/{updateId}",
    summary: "Update project update",
    tag: "Projects",
    params: [pathParam("id"), pathParam("updateId")],
  },
  {
    method: "delete",
    path: "/projects/{id}/updates/{updateId}",
    summary: "Delete project update",
    tag: "Projects",
    params: [pathParam("id"), pathParam("updateId")],
  },
  {
    method: "get",
    path: "/documents",
    summary: "List documents",
    tag: "Documents",
    params: [queryParam("type"), queryParam("page"), queryParam("limit")],
  },
  { method: "post", path: "/documents", summary: "Create document metadata", tag: "Documents" },
  { method: "post", path: "/documents/upload", summary: "Upload document file", tag: "Documents" },
  {
    method: "delete",
    path: "/documents/{id}",
    summary: "Delete document",
    tag: "Documents",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/documents/{id}",
    summary: "Update document",
    tag: "Documents",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/documents/{id}/signed-url",
    summary: "Get signed download URL",
    tag: "Documents",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/documents/{id}/versions",
    summary: "List document versions",
    tag: "Documents",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/documents/{id}/versions/{versionId}",
    summary: "Get document version",
    tag: "Documents",
    params: [pathParam("id"), pathParam("versionId")],
  },
  { method: "post", path: "/documents/bulk/folder", summary: "Bulk folder move", tag: "Documents" },
  {
    method: "post",
    path: "/documents/bulk/metadata",
    summary: "Bulk metadata update",
    tag: "Documents",
  },
];

const billingNotifications: RouteDef[] = [
  { method: "get", path: "/billing/summary", summary: "Get billing summary", tag: "Billing" },
  { method: "get", path: "/billing/invoices", summary: "List invoices", tag: "Billing" },
  {
    method: "get",
    path: "/billing/invoices/{id}",
    summary: "Get invoice",
    tag: "Billing",
    params: [pathParam("id")],
  },
  { method: "get", path: "/billing/subscriptions", summary: "List subscriptions", tag: "Billing" },
  { method: "get", path: "/billing/payments", summary: "List payments", tag: "Billing" },
  {
    method: "post",
    path: "/billing/sync",
    summary: "Sync billing data from Stripe",
    tag: "Billing",
  },
  {
    method: "get",
    path: "/notifications",
    summary: "List notifications",
    tag: "Notifications",
    params: [queryParam("unread"), queryParam("page"), queryParam("limit")],
  },
  {
    method: "get",
    path: "/notifications/unread-count",
    summary: "Get unread count",
    tag: "Notifications",
  },
  {
    method: "get",
    path: "/notifications/stream",
    summary: "SSE stream for real-time notifications",
    tag: "Notifications",
  },
  {
    method: "post",
    path: "/notifications",
    summary: "Create notification (admin)",
    tag: "Notifications",
  },
  {
    method: "post",
    path: "/notifications/{id}/read",
    summary: "Mark notification read",
    tag: "Notifications",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/notifications/mark-all-read",
    summary: "Mark all notifications read",
    tag: "Notifications",
  },
  {
    method: "delete",
    path: "/notifications/{id}",
    summary: "Delete notification",
    tag: "Notifications",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/notification-preferences",
    summary: "Get notification preferences",
    tag: "Notifications",
  },
  {
    method: "put",
    path: "/notification-preferences",
    summary: "Update notification preferences",
    tag: "Notifications",
  },
];

const adminAudit: RouteDef[] = [
  { method: "get", path: "/admin/dashboard", summary: "Admin dashboard data", tag: "Admin" },
  {
    method: "get",
    path: "/audit",
    summary: "List audit logs",
    tag: "Audit",
    params: [
      queryParam("entity_type"),
      queryParam("action"),
      queryParam("page"),
      queryParam("limit"),
    ],
  },
  {
    method: "get",
    path: "/audit/export",
    summary: "Export audit logs (CSV/JSON)",
    tag: "Audit",
    params: [queryParam("format")],
  },
  {
    method: "get",
    path: "/search",
    summary: "Admin global search",
    tag: "Search",
    params: [queryParam("q")],
  },
  {
    method: "get",
    path: "/search/portal",
    summary: "Portal-scoped search",
    tag: "Search",
    params: [queryParam("q")],
  },
  { method: "get", path: "/admin/health", summary: "Health dashboard data", tag: "Admin" },
  { method: "get", path: "/sla", summary: "List SLA metrics", tag: "Admin" },
  { method: "get", path: "/api-keys", summary: "List API keys", tag: "Admin" },
  { method: "post", path: "/api-keys", summary: "Create API key", tag: "Admin" },
  {
    method: "patch",
    path: "/api-keys/{id}",
    summary: "Update API key",
    tag: "Admin",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/api-keys/{id}",
    summary: "Delete API key",
    tag: "Admin",
    params: [pathParam("id")],
  },
];

const systemWebhooks: RouteDef[] = [
  {
    method: "post",
    path: "/webhooks/stripe",
    summary: "Stripe webhook handler",
    tag: "Webhooks",
    auth: false,
  },
  {
    method: "post",
    path: "/webhooks/jira",
    summary: "Jira webhook handler",
    tag: "Webhooks",
    auth: false,
  },
  {
    method: "post",
    path: "/webhooks/jsm",
    summary: "JSM webhook handler",
    tag: "Webhooks",
    auth: false,
  },
  {
    method: "post",
    path: "/webhooks/m365",
    summary: "M365 webhook handler",
    tag: "Webhooks",
    auth: false,
  },
  { method: "get", path: "/webhook-endpoints", summary: "List webhook endpoints", tag: "Webhooks" },
  {
    method: "post",
    path: "/webhook-endpoints",
    summary: "Create webhook endpoint",
    tag: "Webhooks",
  },
  {
    method: "get",
    path: "/webhook-endpoints/{id}",
    summary: "Get webhook endpoint",
    tag: "Webhooks",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/webhook-endpoints/{id}",
    summary: "Update webhook endpoint",
    tag: "Webhooks",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/webhook-endpoints/{id}",
    summary: "Delete webhook endpoint",
    tag: "Webhooks",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/webhook-endpoints/{id}/deliveries",
    summary: "List webhook deliveries",
    tag: "Webhooks",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/webhook-endpoints/{id}/test",
    summary: "Test webhook endpoint",
    tag: "Webhooks",
    params: [pathParam("id")],
  },
  { method: "post", path: "/bulk/invite", summary: "Bulk invite users (CSV)", tag: "Admin" },
  {
    method: "post",
    path: "/public/init",
    summary: "Public init (CSRF token)",
    tag: "Public",
    auth: false,
  },
  {
    method: "post",
    path: "/public/submit",
    summary: "Public form submission",
    tag: "Public",
    auth: false,
  },
];

const businessModules: RouteDef[] = [
  { method: "post", path: "/store/promotions", summary: "Create promotion", tag: "Store" },
  { method: "get", path: "/store/promotions", summary: "List promotions", tag: "Store" },
  {
    method: "get",
    path: "/store/promotions/active",
    summary: "List active promotions (public)",
    tag: "Store",
    auth: false,
  },
  {
    method: "patch",
    path: "/store/promotions/{id}",
    summary: "Update promotion",
    tag: "Store",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/store/promotions/{id}",
    summary: "Delete promotion",
    tag: "Store",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/store/quotes",
    summary: "Submit quote request",
    tag: "Store",
    auth: false,
  },
  { method: "get", path: "/store/quotes", summary: "List quote requests (admin)", tag: "Store" },
  {
    method: "get",
    path: "/store/quotes/{id}",
    summary: "Get quote request",
    tag: "Store",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/store/products",
    summary: "List products (public)",
    tag: "Store",
    auth: false,
    params: [queryParam("category")],
  },
  {
    method: "get",
    path: "/store/products/{slug}",
    summary: "Get product by slug (public)",
    tag: "Store",
    auth: false,
    params: [pathParam("slug")],
  },
  {
    method: "get",
    path: "/store/categories",
    summary: "List categories (public)",
    tag: "Store",
    auth: false,
  },
  {
    method: "get",
    path: "/store/categories/{slug}",
    summary: "Get category with products (public)",
    tag: "Store",
    auth: false,
    params: [pathParam("slug")],
  },
  {
    method: "post",
    path: "/analytics/track",
    summary: "Track analytics event (public)",
    tag: "Analytics",
    auth: false,
  },
  { method: "get", path: "/analytics", summary: "List analytics events (admin)", tag: "Analytics" },
  { method: "get", path: "/proposals", summary: "List proposals", tag: "Proposals" },
  { method: "post", path: "/proposals", summary: "Create proposal", tag: "Proposals" },
  {
    method: "get",
    path: "/proposals/{id}",
    summary: "Get proposal",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/proposals/{id}",
    summary: "Update proposal",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/proposals/{id}",
    summary: "Delete proposal",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  { method: "get", path: "/findings", summary: "List findings", tag: "Findings" },
  {
    method: "get",
    path: "/findings/export",
    summary: "Export findings (CSV/JSON)",
    tag: "Findings",
    params: [queryParam("format")],
  },
  { method: "post", path: "/findings", summary: "Create finding", tag: "Findings" },
  {
    method: "get",
    path: "/findings/{id}",
    summary: "Get finding",
    tag: "Findings",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/findings/{id}",
    summary: "Update finding",
    tag: "Findings",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/findings/{id}",
    summary: "Delete finding",
    tag: "Findings",
    params: [pathParam("id")],
  },
  { method: "get", path: "/governance/policies", summary: "List policies", tag: "Governance" },
  { method: "post", path: "/governance/policies", summary: "Create policy", tag: "Governance" },
  {
    method: "get",
    path: "/governance/policies/{id}",
    summary: "Get policy",
    tag: "Governance",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/governance/policies/{id}",
    summary: "Update policy",
    tag: "Governance",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/governance/policies/{id}",
    summary: "Delete policy",
    tag: "Governance",
    params: [pathParam("id")],
  },
  { method: "get", path: "/governance/controls", summary: "List controls", tag: "Governance" },
  {
    method: "get",
    path: "/governance/controls/{id}",
    summary: "Get control",
    tag: "Governance",
    params: [pathParam("id")],
  },
  { method: "get", path: "/governance/risks", summary: "List risks", tag: "Governance" },
  { method: "post", path: "/governance/risks", summary: "Create risk", tag: "Governance" },
  {
    method: "post",
    path: "/governance/risks/{id}/assess",
    summary: "Assess risk",
    tag: "Governance",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/service-catalog",
    summary: "List service catalog",
    tag: "ServiceCatalog",
  },
  {
    method: "get",
    path: "/service-catalog/{id}",
    summary: "Get service catalog item",
    tag: "ServiceCatalog",
    params: [pathParam("id")],
  },
  { method: "post", path: "/business-os", summary: "Get business OS summary", tag: "BusinessOS" },
  { method: "get", path: "/assets", summary: "List assets", tag: "Assets" },
  { method: "get", path: "/assets/stats", summary: "Asset statistics", tag: "Assets" },
  {
    method: "get",
    path: "/assets/export",
    summary: "Export assets (CSV/JSON)",
    tag: "Assets",
    params: [queryParam("format")],
  },
  { method: "post", path: "/assets", summary: "Create asset", tag: "Assets" },
  {
    method: "get",
    path: "/assets/{id}",
    summary: "Get asset",
    tag: "Assets",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/assets/{id}",
    summary: "Update asset",
    tag: "Assets",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/assets/{id}",
    summary: "Delete asset",
    tag: "Assets",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/assets/{id}/comments",
    summary: "Add asset comment",
    tag: "Assets",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/domain-monitors",
    summary: "List domain monitors",
    tag: "DomainMonitors",
  },
  {
    method: "get",
    path: "/domain-monitors/stats",
    summary: "Domain monitor statistics",
    tag: "DomainMonitors",
  },
  {
    method: "get",
    path: "/domain-monitors/export",
    summary: "Export domain monitors",
    tag: "DomainMonitors",
    params: [queryParam("format")],
  },
  {
    method: "post",
    path: "/domain-monitors",
    summary: "Create domain monitor",
    tag: "DomainMonitors",
  },
  {
    method: "get",
    path: "/domain-monitors/{id}",
    summary: "Get domain monitor",
    tag: "DomainMonitors",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/domain-monitors/{id}",
    summary: "Update domain monitor",
    tag: "DomainMonitors",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/domain-monitors/{id}",
    summary: "Delete domain monitor",
    tag: "DomainMonitors",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/domain-monitors/{id}/scan",
    summary: "Trigger domain scan",
    tag: "DomainMonitors",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/security-suite",
    summary: "Security suite summary",
    tag: "SecuritySuite",
  },
  {
    method: "post",
    path: "/security-suite/m365-hardening/{id}/scan",
    summary: "Run M365 hardening scan",
    tag: "SecuritySuite",
    params: [pathParam("id")],
  },
  { method: "get", path: "/security-ops", summary: "Security ops summary", tag: "SecurityOps" },
  {
    method: "get",
    path: "/field-services",
    summary: "Field services summary",
    tag: "FieldServices",
  },
  {
    method: "get",
    path: "/edu-automation",
    summary: "Education automation summary",
    tag: "EduAutomation",
  },
  { method: "get", path: "/file-requests", summary: "List file requests", tag: "FileRequests" },
  { method: "post", path: "/file-requests", summary: "Create file request", tag: "FileRequests" },
  {
    method: "get",
    path: "/file-requests/{id}",
    summary: "Get file request",
    tag: "FileRequests",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/file-requests/{id}/upload",
    summary: "Upload to file request",
    tag: "FileRequests",
    params: [pathParam("id")],
  },
  { method: "get", path: "/approvals", summary: "List approvals", tag: "Approvals" },
  {
    method: "get",
    path: "/approvals/export",
    summary: "Export approvals (CSV/JSON)",
    tag: "Approvals",
    params: [queryParam("format")],
  },
  { method: "post", path: "/approvals", summary: "Create approval request", tag: "Approvals" },
  {
    method: "get",
    path: "/approvals/{id}",
    summary: "Get approval",
    tag: "Approvals",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/approvals/{id}",
    summary: "Update approval",
    tag: "Approvals",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/approvals/{id}/approve",
    summary: "Approve/reject",
    tag: "Approvals",
    params: [pathParam("id")],
  },
  { method: "get", path: "/vendors", summary: "List vendors", tag: "Vendors" },
  {
    method: "get",
    path: "/vendors/export",
    summary: "Export vendors",
    tag: "Vendors",
    params: [queryParam("format")],
  },
  { method: "post", path: "/vendors", summary: "Create vendor", tag: "Vendors" },
  {
    method: "get",
    path: "/vendors/{id}",
    summary: "Get vendor",
    tag: "Vendors",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/vendors/{id}",
    summary: "Update vendor",
    tag: "Vendors",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/vendors/{id}",
    summary: "Delete vendor",
    tag: "Vendors",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/vendors/{id}/contracts",
    summary: "List vendor contracts",
    tag: "Vendors",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/vendors/{id}/contracts",
    summary: "Add vendor contract",
    tag: "Vendors",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/vendors/{id}/contacts",
    summary: "List vendor contacts",
    tag: "Vendors",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/vendors/{id}/contacts",
    summary: "Add vendor contact",
    tag: "Vendors",
    params: [pathParam("id")],
  },
  { method: "get", path: "/qbr", summary: "List QBR reports", tag: "QBR" },
  { method: "post", path: "/qbr", summary: "Create QBR report", tag: "QBR" },
  {
    method: "get",
    path: "/qbr/{id}",
    summary: "Get QBR report",
    tag: "QBR",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/qbr/{id}",
    summary: "Update QBR report",
    tag: "QBR",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/qbr/{id}",
    summary: "Delete QBR report",
    tag: "QBR",
    params: [pathParam("id")],
  },
  { method: "get", path: "/dmarc-coach", summary: "List DMARC assessments", tag: "DMARCCoach" },
  {
    method: "post",
    path: "/dmarc-coach/scan/{id}",
    summary: "Run DMARC scan",
    tag: "DMARCCoach",
    params: [pathParam("id")],
  },
  { method: "get", path: "/uptime-monitor", summary: "List uptime monitors", tag: "UptimeMonitor" },
  {
    method: "post",
    path: "/uptime-monitor/{id}/check",
    summary: "Run uptime check",
    tag: "UptimeMonitor",
    params: [pathParam("id")],
  },
  { method: "get", path: "/status-page", summary: "List status pages", tag: "StatusPage" },
  { method: "get", path: "/training-hub", summary: "List training modules", tag: "TrainingHub" },
  {
    method: "get",
    path: "/license-optimizer",
    summary: "License optimizer summary",
    tag: "LicenseOptimizer",
  },
  { method: "get", path: "/ai", summary: "List AI tools", tag: "AI" },
  {
    method: "post",
    path: "/ai/{id}/generate",
    summary: "Generate AI content",
    tag: "AI",
    params: [pathParam("id")],
  },
  { method: "get", path: "/batch", summary: "List batch operations", tag: "Batch" },
  { method: "post", path: "/batch", summary: "Submit batch operation", tag: "Batch" },
  { method: "get", path: "/sop-library", summary: "List SOPs", tag: "SOP" },
  {
    method: "get",
    path: "/sop-library/{id}",
    summary: "Get SOP",
    tag: "SOP",
    params: [pathParam("id")],
  },
  { method: "get", path: "/final", summary: "List final assessments", tag: "Final" },
  { method: "post", path: "/final", summary: "Create final assessment", tag: "Final" },
  {
    method: "get",
    path: "/client-onboarding",
    summary: "Client onboarding status",
    tag: "Onboarding",
  },
  {
    method: "get",
    path: "/satisfaction-pulse",
    summary: "Satisfaction pulse surveys",
    tag: "Satisfaction",
  },
  { method: "get", path: "/dynamic-forms", summary: "Dynamic forms", tag: "Forms" },
  { method: "get", path: "/insurance-binder", summary: "Insurance binder", tag: "Insurance" },
  { method: "get", path: "/dashboard/summary", summary: "Dashboard summary", tag: "Dashboard" },
  {
    method: "get",
    path: "/dashboard/activity-feed",
    summary: "Recent activity feed",
    tag: "Dashboard",
  },
];

const extendedRoutes: RouteDef[] = [
  // admin - generated from apps/api/src/routes/admin.ts
  { method: "post", path: "/admin/test-email", summary: "Send test email", tag: "Admin" },

  // ai - generated from apps/api/src/routes/ai.ts
  { method: "post", path: "/ai/triage/analyze", summary: "Analyze tickets with AI", tag: "AI" },
  {
    method: "post",
    path: "/ai/triage/convert",
    summary: "Convert AI triage result to ticket",
    tag: "AI",
  },
  { method: "get", path: "/ai/triage", summary: "Get AI triage suggestions", tag: "AI" },
  {
    method: "get",
    path: "/ai/copilot/{ticketId}/summarize",
    summary: "Summarize ticket with AI",
    tag: "AI",
    params: [pathParam("ticketId")],
  },
  {
    method: "post",
    path: "/ai/copilot/{ticketId}/reply-draft",
    summary: "Draft AI reply for ticket",
    tag: "AI",
    params: [pathParam("ticketId")],
  },

  // analytics - generated from apps/api/src/routes/analytics.ts
  { method: "get", path: "/analytics/summary", summary: "Get analytics summary", tag: "Analytics" },

  // approvals - generated from apps/api/src/routes/approvals.ts
  { method: "get", path: "/approvals/stats", summary: "Get approval statistics", tag: "Approvals" },
  {
    method: "delete",
    path: "/approvals/{id}",
    summary: "Delete approval",
    tag: "Approvals",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/approvals/{id}/reject",
    summary: "Reject approval",
    tag: "Approvals",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/approvals/{id}/cancel",
    summary: "Cancel approval",
    tag: "Approvals",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/approvals/{id}/comments",
    summary: "List approval comments",
    tag: "Approvals",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/approvals/{id}/comments",
    summary: "Add approval comment",
    tag: "Approvals",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/approvals/{id}/timeline",
    summary: "Get approval timeline",
    tag: "Approvals",
    params: [pathParam("id")],
  },

  // assets - generated from apps/api/src/routes/assets.ts
  {
    method: "get",
    path: "/assets/{id}/comments",
    summary: "List asset comments",
    tag: "Assets",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/assets/{id}/timeline",
    summary: "Get asset timeline",
    tag: "Assets",
    params: [pathParam("id")],
  },

  // batch - generated from apps/api/src/routes/batch.ts
  {
    method: "get",
    path: "/batch/status/public",
    summary: "List public status items",
    tag: "Batch",
    auth: false,
  },
  { method: "get", path: "/batch/licenses/savings", summary: "Get license savings", tag: "Batch" },

  // billing - generated from apps/api/src/routes/billing.ts
  {
    method: "get",
    path: "/billing/billing-customer",
    summary: "Get Stripe billing customer",
    tag: "Billing",
  },
  {
    method: "post",
    path: "/billing/create-portal-session",
    summary: "Create billing portal session",
    tag: "Billing",
  },

  // business-os - generated from apps/api/src/routes/business-os.ts
  {
    method: "get",
    path: "/business-os/summary",
    summary: "Get business OS summary",
    tag: "BusinessOS",
  },
  {
    method: "get",
    path: "/business-os/approvals-overdue",
    summary: "Get overdue approvals",
    tag: "BusinessOS",
  },
  {
    method: "get",
    path: "/business-os/recent-activity",
    summary: "Get recent activity",
    tag: "BusinessOS",
  },
  { method: "get", path: "/business-os/org-health", summary: "Get org health", tag: "BusinessOS" },

  // client-onboarding-command-center - generated from apps/api/src/routes/client-onboarding-command-center.ts
  {
    method: "get",
    path: "/client-onboarding/export.csv",
    summary: "Export client onboarding (CSV)",
    tag: "Onboarding",
  },
  {
    method: "get",
    path: "/client-onboarding/{id}",
    summary: "Get client onboarding",
    tag: "Onboarding",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/client-onboarding",
    summary: "Create client onboarding",
    tag: "Onboarding",
  },
  {
    method: "patch",
    path: "/client-onboarding/{id}",
    summary: "Update client onboarding",
    tag: "Onboarding",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/client-onboarding/{id}",
    summary: "Delete client onboarding",
    tag: "Onboarding",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/client-onboarding/{id}/complete-phase",
    summary: "Complete onboarding phase",
    tag: "Onboarding",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/client-onboarding/{id}/checklist",
    summary: "Get onboarding checklist",
    tag: "Onboarding",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/client-onboarding/{id}/checklist/{itemId}",
    summary: "Update onboarding checklist item",
    tag: "Onboarding",
    params: [pathParam("id"), pathParam("itemId")],
  },

  // dmarc-coach - generated from apps/api/src/routes/dmarc-coach.ts
  {
    method: "get",
    path: "/dmarc-coach/{id}",
    summary: "Get DMARC assessment",
    tag: "DMARCCoach",
    params: [pathParam("id")],
  },
  { method: "post", path: "/dmarc-coach", summary: "Create DMARC assessment", tag: "DMARCCoach" },
  {
    method: "patch",
    path: "/dmarc-coach/{id}",
    summary: "Update DMARC assessment",
    tag: "DMARCCoach",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/dmarc-coach/{id}",
    summary: "Delete DMARC assessment",
    tag: "DMARCCoach",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/dmarc-coach/analyze",
    summary: "Run DMARC analysis",
    tag: "DMARCCoach",
  },

  // documents - generated from apps/api/src/routes/documents.ts
  {
    method: "get",
    path: "/documents/{id}",
    summary: "Get document",
    tag: "Documents",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/documents/{id}/signed-url",
    summary: "Create signed download URL",
    tag: "Documents",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/documents/{id}/shares",
    summary: "Create document share link",
    tag: "Documents",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/documents/{id}/shares",
    summary: "List document shares",
    tag: "Documents",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/documents/{id}/shares/{shareId}",
    summary: "Update document share",
    tag: "Documents",
    params: [pathParam("id"), pathParam("shareId")],
  },
  {
    method: "delete",
    path: "/documents/{id}/shares/{shareId}",
    summary: "Delete document share",
    tag: "Documents",
    params: [pathParam("id"), pathParam("shareId")],
  },
  {
    method: "get",
    path: "/documents/shares/{token}",
    summary: "Get shared document by token (public)",
    tag: "Documents",
    auth: false,
    params: [pathParam("token")],
  },

  // dynamic-client-forms-builder - generated from apps/api/src/routes/dynamic-client-forms-builder.ts
  {
    method: "get",
    path: "/dynamic-forms/export.csv",
    summary: "Export dynamic forms (CSV)",
    tag: "Forms",
  },
  {
    method: "get",
    path: "/dynamic-forms/{id}",
    summary: "Get dynamic form",
    tag: "Forms",
    params: [pathParam("id")],
  },
  { method: "post", path: "/dynamic-forms", summary: "Create dynamic form", tag: "Forms" },
  {
    method: "patch",
    path: "/dynamic-forms/{id}",
    summary: "Update dynamic form",
    tag: "Forms",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/dynamic-forms/{id}",
    summary: "Delete dynamic form",
    tag: "Forms",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/dynamic-forms/{id}/publish",
    summary: "Publish dynamic form",
    tag: "Forms",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/dynamic-forms/{id}/submit",
    summary: "Submit dynamic form response",
    tag: "Forms",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/dynamic-forms/{id}/submissions",
    summary: "List form submissions",
    tag: "Forms",
    params: [pathParam("id")],
  },

  // edu-automation - generated from apps/api/src/routes/edu-automation.ts
  {
    method: "post",
    path: "/edu-automation/automation/{id}/execute",
    summary: "Execute automation",
    tag: "EduAutomation",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/edu-automation/automation/{id}/complete",
    summary: "Complete automation",
    tag: "EduAutomation",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/edu-automation/kb-generator/{id}/generate",
    summary: "Generate knowledge base article",
    tag: "EduAutomation",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/edu-automation/kb/search",
    summary: "Search knowledge base",
    tag: "EduAutomation",
  },
  {
    method: "post",
    path: "/edu-automation/kb/{id}/rate",
    summary: "Rate knowledge base article",
    tag: "EduAutomation",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/edu-automation/compliance/score",
    summary: "Score compliance posture",
    tag: "EduAutomation",
  },
  {
    method: "post",
    path: "/edu-automation/phishing/{id}/launch",
    summary: "Launch phishing campaign",
    tag: "EduAutomation",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/edu-automation/phishing/{id}/results",
    summary: "Get phishing campaign results",
    tag: "EduAutomation",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/edu-automation/scorecards/summary",
    summary: "Get scorecard summary",
    tag: "EduAutomation",
  },
  {
    method: "get",
    path: "/edu-automation/scorecards/overview",
    summary: "Get scorecard overview",
    tag: "EduAutomation",
  },
  {
    method: "get",
    path: "/edu-automation/scorecards/leaderboard",
    summary: "Get scorecard leaderboard",
    tag: "EduAutomation",
  },
  {
    method: "post",
    path: "/edu-automation/scorecards/evaluate",
    summary: "Evaluate scorecard",
    tag: "EduAutomation",
  },

  // field-services - generated from apps/api/src/routes/field-services.ts
  {
    method: "post",
    path: "/field-services/isp/{id}/score",
    summary: "Score ISP offering",
    tag: "FieldServices",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/field-services/unifi/{id}/plan",
    summary: "Generate UniFi deployment plan",
    tag: "FieldServices",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/field-services/camera-calc/calculate",
    summary: "Calculate camera coverage plan",
    tag: "FieldServices",
  },
  {
    method: "post",
    path: "/field-services/staging/{id}/checklist",
    summary: "Get hardware staging checklist",
    tag: "FieldServices",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/field-services/network-diagrams/{id}/export",
    summary: "Export network diagram",
    tag: "FieldServices",
    params: [pathParam("id")],
  },

  // file-requests - generated from apps/api/src/routes/file-requests.ts
  {
    method: "get",
    path: "/file-requests/public/{token}",
    summary: "Get public file request by token",
    tag: "FileRequests",
    auth: false,
    params: [pathParam("token")],
  },
  {
    method: "patch",
    path: "/file-requests/{id}",
    summary: "Update file request",
    tag: "FileRequests",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/file-requests/{id}",
    summary: "Delete file request",
    tag: "FileRequests",
    params: [pathParam("id")],
  },

  // final - generated from apps/api/src/routes/final.ts
  {
    method: "get",
    path: "/final/sharepoint/structure-summary",
    summary: "Get SharePoint structure summary",
    tag: "Final",
  },
  { method: "get", path: "/final/backups/stats", summary: "Get backup statistics", tag: "Final" },
  {
    method: "get",
    path: "/final/backups/risk-analysis",
    summary: "Get backup risk analysis",
    tag: "Final",
  },
  { method: "get", path: "/final/budgets/analysis", summary: "Get budget analysis", tag: "Final" },
  {
    method: "post",
    path: "/final/procurement/compare",
    summary: "Compare procurement options",
    tag: "Final",
  },
  {
    method: "post",
    path: "/final/dns-changes/{id}/approve",
    summary: "Approve DNS change request",
    tag: "Final",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/final/dns-changes/{id}/reject",
    summary: "Reject DNS change request",
    tag: "Final",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/final/dns-changes/{id}/implement",
    summary: "Implement DNS change request",
    tag: "Final",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/final/time-entries/summary",
    summary: "Summarize time entries by period",
    tag: "Final",
  },

  // findings - generated from apps/api/src/routes/findings.ts
  { method: "get", path: "/findings/stats", summary: "Get finding statistics", tag: "Findings" },
  {
    method: "post",
    path: "/findings/{id}/verify",
    summary: "Verify finding",
    tag: "Findings",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/findings/{id}/resolve",
    summary: "Resolve finding",
    tag: "Findings",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/findings/{id}/comments",
    summary: "List finding comments",
    tag: "Findings",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/findings/{id}/comments",
    summary: "Add finding comment",
    tag: "Findings",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/findings/{id}/timeline",
    summary: "Get finding timeline",
    tag: "Findings",
    params: [pathParam("id")],
  },

  // governance - generated from apps/api/src/routes/governance.ts
  {
    method: "post",
    path: "/governance/change-requests/{id}/submit",
    summary: "Submit change request",
    tag: "Governance",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/governance/change-requests/{id}/approve",
    summary: "Approve change request",
    tag: "Governance",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/governance/change-requests/{id}/reject",
    summary: "Reject change request",
    tag: "Governance",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/governance/change-requests/{id}/implement",
    summary: "Implement change request",
    tag: "Governance",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/governance/change-requests/{id}/verify",
    summary: "Verify change request",
    tag: "Governance",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/governance/sop-library/compliance-map",
    summary: "Get SOP compliance map",
    tag: "Governance",
  },
  {
    method: "get",
    path: "/governance/sop-library/framework-gaps",
    summary: "Get framework gaps",
    tag: "Governance",
  },

  // health - generated from apps/api/src/routes/health.ts
  { method: "get", path: "/health", summary: "Health check", tag: "Health", auth: false },

  // insurance-binder - generated from apps/api/src/routes/insurance-binder.ts
  {
    method: "get",
    path: "/insurance-binder/coverage-report",
    summary: "Get coverage report",
    tag: "Insurance",
  },
  {
    method: "post",
    path: "/insurance-binder",
    summary: "Create insurance binder",
    tag: "Insurance",
  },
  {
    method: "get",
    path: "/insurance-binder/{id}",
    summary: "Get insurance binder",
    tag: "Insurance",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/insurance-binder/{id}",
    summary: "Update insurance binder",
    tag: "Insurance",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/insurance-binder/{id}",
    summary: "Delete insurance binder",
    tag: "Insurance",
    params: [pathParam("id")],
  },

  // license-optimizer - generated from apps/api/src/routes/license-optimizer.ts
  {
    method: "get",
    path: "/license-optimizer/{id}",
    summary: "Get license optimizer run",
    tag: "LicenseOptimizer",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/license-optimizer",
    summary: "Create license optimizer run",
    tag: "LicenseOptimizer",
  },
  {
    method: "patch",
    path: "/license-optimizer/{id}",
    summary: "Update license optimizer run",
    tag: "LicenseOptimizer",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/license-optimizer/{id}",
    summary: "Delete license optimizer run",
    tag: "LicenseOptimizer",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/license-optimizer/reclaimable/license-list",
    summary: "Get reclaimable license list",
    tag: "LicenseOptimizer",
  },
  {
    method: "get",
    path: "/license-optimizer/summary/data",
    summary: "Get license optimizer summary",
    tag: "LicenseOptimizer",
  },

  // profiles - generated from apps/api/src/routes/profiles.ts
  {
    method: "get",
    path: "/profiles/{id}",
    summary: "Get profile",
    tag: "Profiles",
    params: [pathParam("id")],
  },

  // projects - generated from apps/api/src/routes/projects.ts
  {
    method: "delete",
    path: "/projects/{id}/tasks/{taskId}/comments/{commentId}",
    summary: "Delete task comment",
    tag: "Projects",
    params: [pathParam("id"), pathParam("taskId"), pathParam("commentId")],
  },

  // proposals - generated from apps/api/src/routes/proposals.ts
  {
    method: "get",
    path: "/proposals/export",
    summary: "Export proposals (CSV/JSON)",
    tag: "Proposals",
  },
  {
    method: "post",
    path: "/proposals/{id}/phases",
    summary: "Create phase",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/proposals/{id}/phases/{phaseId}",
    summary: "Update phase",
    tag: "Proposals",
    params: [pathParam("id"), pathParam("phaseId")],
  },
  {
    method: "delete",
    path: "/proposals/{id}/phases/{phaseId}",
    summary: "Delete phase",
    tag: "Proposals",
    params: [pathParam("id"), pathParam("phaseId")],
  },
  {
    method: "post",
    path: "/proposals/{id}/items",
    summary: "Create item",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/proposals/{id}/items/{itemId}",
    summary: "Update item",
    tag: "Proposals",
    params: [pathParam("id"), pathParam("itemId")],
  },
  {
    method: "delete",
    path: "/proposals/{id}/items/{itemId}",
    summary: "Delete item",
    tag: "Proposals",
    params: [pathParam("id"), pathParam("itemId")],
  },
  {
    method: "post",
    path: "/proposals/{id}/submit-approval",
    summary: "Submit proposal for approval",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/proposals/{id}/publish",
    summary: "Publish proposal",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/proposals/{id}/comments",
    summary: "List proposal comments",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/proposals/{id}/comments",
    summary: "Add proposal comment",
    tag: "Proposals",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/proposals/{id}/timeline",
    summary: "Get proposal timeline",
    tag: "Proposals",
    params: [pathParam("id")],
  },

  // public - generated from apps/api/src/routes/public.ts
  {
    method: "get",
    path: "/public/init",
    summary: "Public init (CSRF token)",
    tag: "Public",
    auth: false,
  },

  // qbr - generated from apps/api/src/routes/qbr.ts
  { method: "post", path: "/qbr/generate", summary: "Generate QBR report", tag: "QBR" },

  // satisfaction-pulse-widget - generated from apps/api/src/routes/satisfaction-pulse-widget.ts
  {
    method: "get",
    path: "/satisfaction-pulse/export",
    summary: "Export surveys (CSV/JSON)",
    tag: "Satisfaction",
  },
  {
    method: "get",
    path: "/satisfaction-pulse/{id}",
    summary: "Get survey",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },
  { method: "post", path: "/satisfaction-pulse", summary: "Create survey", tag: "Satisfaction" },
  {
    method: "patch",
    path: "/satisfaction-pulse/{id}",
    summary: "Update survey",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/satisfaction-pulse/{id}/respond",
    summary: "Submit survey response",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/satisfaction-pulse/{id}",
    summary: "Delete survey",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/satisfaction-pulse/templates",
    summary: "List templates",
    tag: "Satisfaction",
  },
  {
    method: "get",
    path: "/satisfaction-pulse/templates/{id}",
    summary: "Get template",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/satisfaction-pulse/templates",
    summary: "Create template",
    tag: "Satisfaction",
  },
  {
    method: "patch",
    path: "/satisfaction-pulse/templates/{id}",
    summary: "Update template",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/satisfaction-pulse/templates/{id}",
    summary: "Delete template",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/satisfaction-pulse/schedules",
    summary: "List schedules",
    tag: "Satisfaction",
  },
  {
    method: "post",
    path: "/satisfaction-pulse/schedules",
    summary: "Create schedule",
    tag: "Satisfaction",
  },
  {
    method: "patch",
    path: "/satisfaction-pulse/schedules/{id}",
    summary: "Update schedule",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/satisfaction-pulse/schedules/{id}",
    summary: "Delete schedule",
    tag: "Satisfaction",
    params: [pathParam("id")],
  },

  // security-ops - generated from apps/api/src/routes/security-ops.ts
  {
    method: "post",
    path: "/security-ops/offboarding/{id}/complete-step",
    summary: "Complete offboarding step",
    tag: "SecurityOps",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/security-ops/patch-compliance/stats",
    summary: "Get patch compliance stats",
    tag: "SecurityOps",
  },

  // security-suite - generated from apps/api/src/routes/security-suite.ts
  {
    method: "post",
    path: "/security-suite/identity-verification/{id}/verify",
    summary: "Verify identity verification",
    tag: "SecuritySuite",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/security-suite/endpoint-security/coverage",
    summary: "Get endpoint security coverage",
    tag: "SecuritySuite",
  },

  // service-catalog - generated from apps/api/src/routes/service-catalog.ts
  {
    method: "post",
    path: "/service-catalog",
    summary: "Create service catalog item",
    tag: "ServiceCatalog",
  },
  {
    method: "patch",
    path: "/service-catalog/{id}",
    summary: "Update service catalog item",
    tag: "ServiceCatalog",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/service-catalog/{id}",
    summary: "Delete service catalog item",
    tag: "ServiceCatalog",
    params: [pathParam("id")],
  },

  // sla - generated from apps/api/src/routes/sla.ts
  { method: "get", path: "/sla/metrics", summary: "Get SLA metrics", tag: "SLA" },

  // status-page - generated from apps/api/src/routes/status-page.ts
  {
    method: "get",
    path: "/status-page/public/{orgId}",
    summary: "Get public status page",
    tag: "StatusPage",
    auth: false,
    params: [pathParam("orgId")],
  },

  // store - generated from apps/api/src/routes/store.ts
  {
    method: "get",
    path: "/store/promotions/admin",
    summary: "List promotions (admin)",
    tag: "Store",
  },

  // training-hub - generated from apps/api/src/routes/training-hub.ts
  {
    method: "get",
    path: "/training-hub/my-courses",
    summary: "Get my courses",
    tag: "TrainingHub",
  },
  { method: "get", path: "/training-hub/courses", summary: "List courses", tag: "TrainingHub" },
  { method: "post", path: "/training-hub/courses", summary: "Create course", tag: "TrainingHub" },
  {
    method: "get",
    path: "/training-hub/courses/{id}",
    summary: "Get course",
    tag: "TrainingHub",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/training-hub/courses/{id}",
    summary: "Update course",
    tag: "TrainingHub",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/training-hub/courses/{id}",
    summary: "Delete course",
    tag: "TrainingHub",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/training-hub/courses/{id}/enroll",
    summary: "Enroll in course",
    tag: "TrainingHub",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/training-hub/courses/{id}/progress",
    summary: "Update course progress",
    tag: "TrainingHub",
    params: [pathParam("id")],
  },
  { method: "get", path: "/training-hub/lessons", summary: "List lessons", tag: "TrainingHub" },
  { method: "post", path: "/training-hub/lessons", summary: "Create lesson", tag: "TrainingHub" },
  {
    method: "get",
    path: "/training-hub/lessons/{id}",
    summary: "Get lesson",
    tag: "TrainingHub",
    params: [pathParam("id")],
  },
  {
    method: "patch",
    path: "/training-hub/lessons/{id}",
    summary: "Update lesson",
    tag: "TrainingHub",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/training-hub/lessons/{id}",
    summary: "Delete lesson",
    tag: "TrainingHub",
    params: [pathParam("id")],
  },

  // uptime-monitor - generated from apps/api/src/routes/uptime-monitor.ts
  {
    method: "get",
    path: "/uptime-monitor/dashboard",
    summary: "Get uptime monitor dashboard",
    tag: "UptimeMonitor",
  },
  { method: "get", path: "/uptime-monitor/checks", summary: "List checks", tag: "UptimeMonitor" },
  {
    method: "get",
    path: "/uptime-monitor/checks/{id}",
    summary: "Get check",
    tag: "UptimeMonitor",
    params: [pathParam("id")],
  },
  {
    method: "post",
    path: "/uptime-monitor/checks",
    summary: "Create uptime check",
    tag: "UptimeMonitor",
  },
  {
    method: "patch",
    path: "/uptime-monitor/checks/{id}",
    summary: "Update uptime check",
    tag: "UptimeMonitor",
    params: [pathParam("id")],
  },
  {
    method: "delete",
    path: "/uptime-monitor/checks/{id}",
    summary: "Delete uptime check",
    tag: "UptimeMonitor",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/uptime-monitor/checks/{id}/results",
    summary: "List check results",
    tag: "UptimeMonitor",
    params: [pathParam("id")],
  },
  {
    method: "get",
    path: "/uptime-monitor/checks/{id}/uptime",
    summary: "Get uptime percentage",
    tag: "UptimeMonitor",
    params: [pathParam("id")],
  },

  // users - generated from apps/api/src/routes/users.ts
  { method: "get", path: "/users/compound", summary: "Get compound user list", tag: "Users" },

  // vendors - generated from apps/api/src/routes/vendors.ts
  {
    method: "get",
    path: "/vendors/vendor-contracts/renewals",
    summary: "Get vendor contract renewals",
    tag: "Vendors",
  },

  // webhooks - generated from apps/api/src/routes/webhooks.ts
  {
    method: "get",
    path: "/webhooks/m365",
    summary: "M365 OAuth verification challenge",
    tag: "Webhooks",
    auth: false,
  },
];

// Supplemental coverage (P2-8): concrete endpoints that were missing from the
// hand-maintained route groups above. These are derived from a route-tree audit
// (scripts/openapi-audit.js) minus programmatically-built template-literal routes.
// Kept intentionally terse — the goal is documentation coverage, not exhaustive
// schema modeling for every field.
const supplementalCoverage: RouteDef[] = [
  { method: "get", path: "/health", summary: "API health check", tag: "System", auth: false },
  { method: "get", path: "/metrics", summary: "Prometheus metrics", tag: "System", auth: false },
  { method: "get", path: "/docs", summary: "Swagger UI docs", tag: "System", auth: false },
  { method: "get", path: "/openapi.json", summary: "OpenAPI specification", tag: "System", auth: false },
  { method: "get", path: "/me", summary: "Current user profile + memberships", tag: "Me" },
  { method: "patch", path: "/me", summary: "Update current user profile", tag: "Me" },
  {
    method: "get",
    path: "/auth/callback",
    summary: "OAuth/session callback",
    tag: "Auth",
    auth: false,
  },
  { method: "post", path: "/auth/sign-out", summary: "Sign out", tag: "Auth", auth: false },
  { method: "get", path: "/store/products", summary: "List store products", tag: "Store", auth: false },
  { method: "get", path: "/store/products/:slug", summary: "Get store product by slug", tag: "Store", auth: false },
  { method: "get", path: "/store/categories", summary: "List store categories", tag: "Store", auth: false },
  {
    method: "get",
    path: "/store/categories/:slug",
    summary: "Get store category by slug",
    tag: "Store",
    auth: false,
  },
  { method: "get", path: "/store/promotions/active", summary: "List active promotions", tag: "Store", auth: false },
  { method: "get", path: "/store/promotions", summary: "List promotions (admin)", tag: "Store" },
  { method: "get", path: "/store/promotions/admin", summary: "Admin promotion list", tag: "Store" },
  { method: "get", path: "/webhooks", summary: "List webhook endpoints", tag: "Webhooks" },
  { method: "post", path: "/webhooks", summary: "Create webhook endpoint", tag: "Webhooks" },
  { method: "get", path: "/webhooks/:id", summary: "Get webhook endpoint", tag: "Webhooks" },
  { method: "patch", path: "/webhooks/:id", summary: "Update webhook endpoint", tag: "Webhooks" },
  { method: "delete", path: "/webhooks/:id", summary: "Delete webhook endpoint", tag: "Webhooks" },
  { method: "get", path: "/webhooks/:id/deliveries", summary: "List webhook deliveries", tag: "Webhooks" },
  { method: "get", path: "/security-suite", summary: "Security suite overview", tag: "Security" },
  { method: "get", path: "/security-ops", summary: "Security ops overview", tag: "Security" },
  { method: "get", path: "/status-page", summary: "Public status page", tag: "Status", auth: false },
  { method: "get", path: "/uptime-monitor", summary: "Uptime monitor status", tag: "Status" },
  { method: "get", path: "/analytics", summary: "Analytics overview", tag: "Analytics" },
  { method: "get", path: "/training-hub/courses", summary: "List training courses", tag: "Training" },
  { method: "get", path: "/training-hub/courses/:id", summary: "Get training course", tag: "Training" },
  { method: "get", path: "/license-optimizer", summary: "License optimizer overview", tag: "Licenses" },
  { method: "get", path: "/dmarc-coach", summary: "DMARC coach overview", tag: "DMARC" },
  { method: "get", path: "/field-services", summary: "Field services overview", tag: "FieldServices" },
  { method: "get", path: "/edu-automation", summary: "Edu automation overview", tag: "Edu" },
  { method: "get", path: "/governance", summary: "Governance overview", tag: "Governance" },
  { method: "get", path: "/final", summary: "Final/consolidated stats", tag: "Final" },
  { method: "get", path: "/client-onboarding-command-center", summary: "Client onboarding command center", tag: "Onboarding" },
  { method: "get", path: "/satisfaction-pulse-widget", summary: "Satisfaction pulse widget", tag: "Satisfaction" },
  { method: "get", path: "/dynamic-client-forms-builder", summary: "Dynamic client forms", tag: "Forms" },
  { method: "get", path: "/insurance-binder", summary: "Insurance binder overview", tag: "Insurance" },
  { method: "get", path: "/service-catalog", summary: "Service catalog", tag: "ServiceCatalog" },
  { method: "get", path: "/vendors", summary: "List vendors", tag: "Vendors" },
  { method: "post", path: "/vendors", summary: "Create vendor", tag: "Vendors" },
  { method: "get", path: "/vendors/:id", summary: "Get vendor", tag: "Vendors" },
  { method: "patch", path: "/vendors/:id", summary: "Update vendor", tag: "Vendors" },
  { method: "delete", path: "/vendors/:id", summary: "Delete vendor", tag: "Vendors" },
  { method: "get", path: "/assets", summary: "List assets", tag: "Assets" },
  { method: "post", path: "/assets", summary: "Create asset", tag: "Assets" },
  { method: "get", path: "/assets/:id", summary: "Get asset", tag: "Assets" },
  { method: "patch", path: "/assets/:id", summary: "Update asset", tag: "Assets" },
  { method: "delete", path: "/assets/:id", summary: "Delete asset", tag: "Assets" },
  { method: "get", path: "/qbr", summary: "List QBR reports", tag: "QBR" },
  { method: "post", path: "/qbr", summary: "Create QBR report", tag: "QBR" },
  { method: "get", path: "/qbr/:id", summary: "Get QBR report", tag: "QBR" },
  { method: "patch", path: "/qbr/:id", summary: "Update QBR report", tag: "QBR" },
  { method: "delete", path: "/qbr/:id", summary: "Delete QBR report", tag: "QBR" },
  { method: "get", path: "/file-requests", summary: "List file requests", tag: "FileRequests" },
  { method: "post", path: "/file-requests", summary: "Create file request", tag: "FileRequests" },
  { method: "get", path: "/file-requests/:id", summary: "Get file request", tag: "FileRequests" },
  { method: "patch", path: "/file-requests/:id", summary: "Update file request", tag: "FileRequests" },
  { method: "delete", path: "/file-requests/:id", summary: "Delete file request", tag: "FileRequests" },
  { method: "get", path: "/ai", summary: "AI assist overview", tag: "AI" },
  { method: "post", path: "/ai", summary: "Run AI assist", tag: "AI" },
  { method: "get", path: "/api-keys", summary: "List API keys", tag: "ApiKeys" },
  { method: "post", path: "/api-keys", summary: "Create API key", tag: "ApiKeys" },
  { method: "delete", path: "/api-keys/:id", summary: "Revoke API key", tag: "ApiKeys" },
  { method: "get", path: "/sla", summary: "List SLA records", tag: "SLA" },
  { method: "get", path: "/approvals", summary: "List approvals", tag: "Approvals" },
  { method: "get", path: "/bulk", summary: "Bulk operations overview", tag: "Bulk" },
  { method: "get", path: "/business-os", summary: "Business OS snapshot", tag: "BusinessOS" },
  { method: "get", path: "/proposals", summary: "List proposals", tag: "Proposals" },
  { method: "post", path: "/proposals", summary: "Create proposal", tag: "Proposals" },
  { method: "get", path: "/proposals/:id", summary: "Get proposal", tag: "Proposals" },
  { method: "patch", path: "/proposals/:id", summary: "Update proposal", tag: "Proposals" },
  { method: "delete", path: "/proposals/:id", summary: "Delete proposal", tag: "Proposals" },
  { method: "get", path: "/findings", summary: "List findings", tag: "Findings" },
  { method: "post", path: "/findings", summary: "Create finding", tag: "Findings" },
  { method: "get", path: "/findings/:id", summary: "Get finding", tag: "Findings" },
  { method: "patch", path: "/findings/:id", summary: "Update finding", tag: "Findings" },
  { method: "delete", path: "/findings/:id", summary: "Delete finding", tag: "Findings" },
  { method: "get", path: "/notifications", summary: "List notifications", tag: "Notifications" },
  { method: "post", path: "/notifications", summary: "Create notification", tag: "Notifications" },
  { method: "get", path: "/notifications/:id", summary: "Get notification", tag: "Notifications" },
  { method: "patch", path: "/notifications/:id", summary: "Update notification", tag: "Notifications" },
  { method: "delete", path: "/notifications/:id", summary: "Delete notification", tag: "Notifications" },
  { method: "get", path: "/notification-preferences", summary: "List notification preferences", tag: "Notifications" },
  { method: "patch", path: "/notification-preferences/:id", summary: "Update notification preference", tag: "Notifications" },
  { method: "get", path: "/billing", summary: "Billing overview", tag: "Billing" },
  { method: "get", path: "/billing/invoices", summary: "List invoices", tag: "Billing" },
  { method: "get", path: "/billing/subscriptions", summary: "List subscriptions", tag: "Billing" },
  { method: "get", path: "/billing/payments", summary: "List payments", tag: "Billing" },
  { method: "get", path: "/admin", summary: "Admin overview", tag: "Admin" },
  { method: "get", path: "/roles", summary: "List roles", tag: "Roles" },
  { method: "get", path: "/memberships", summary: "List memberships", tag: "Memberships" },
  { method: "get", path: "/users", summary: "List users", tag: "Users" },
  { method: "get", path: "/profiles", summary: "List profiles", tag: "Profiles" },
  { method: "get", path: "/organizations", summary: "List organizations", tag: "Organizations" },
  { method: "get", path: "/tickets", summary: "List tickets", tag: "Tickets" },
  { method: "post", path: "/tickets", summary: "Create ticket", tag: "Tickets" },
  { method: "get", path: "/tickets/:id", summary: "Get ticket", tag: "Tickets" },
  { method: "patch", path: "/tickets/:id", summary: "Update ticket", tag: "Tickets" },
  { method: "delete", path: "/tickets/:id", summary: "Delete ticket", tag: "Tickets" },
  { method: "get", path: "/projects", summary: "List projects", tag: "Projects" },
  { method: "post", path: "/projects", summary: "Create project", tag: "Projects" },
  { method: "get", path: "/projects/:id", summary: "Get project", tag: "Projects" },
  { method: "patch", path: "/projects/:id", summary: "Update project", tag: "Projects" },
  { method: "delete", path: "/projects/:id", summary: "Delete project", tag: "Projects" },
  { method: "get", path: "/documents", summary: "List documents", tag: "Documents" },
  { method: "post", path: "/documents", summary: "Upload document", tag: "Documents" },
  { method: "get", path: "/documents/:id", summary: "Get document", tag: "Documents" },
  { method: "delete", path: "/documents/:id", summary: "Delete document", tag: "Documents" },
  { method: "get", path: "/dashboard", summary: "Dashboard summary", tag: "Dashboard" },
  { method: "get", path: "/audit", summary: "List audit logs", tag: "Audit" },
  { method: "get", path: "/search", summary: "Global search", tag: "Search" },
  { method: "get", path: "/search/portal", summary: "Portal search", tag: "Search" },
  { method: "get", path: "/public", summary: "Public endpoints", tag: "Public", auth: false },
  { method: "get", path: "/domain-monitors", summary: "List domain monitors", tag: "DomainMonitors" },
  { method: "post", path: "/domain-monitors", summary: "Create domain monitor", tag: "DomainMonitors" },
  { method: "get", path: "/domain-monitors/:id", summary: "Get domain monitor", tag: "DomainMonitors" },
  { method: "patch", path: "/domain-monitors/:id", summary: "Update domain monitor", tag: "DomainMonitors" },
  { method: "delete", path: "/domain-monitors/:id", summary: "Delete domain monitor", tag: "DomainMonitors" },
];

export const routeModules: RouteDef[] = [
  ...auth,
  ...auth2,
  ...ticketsProjects,
  ...billingNotifications,
  ...adminAudit,
  ...systemWebhooks,
  ...businessModules,
  ...extendedRoutes,
  ...supplementalCoverage,
];

export function buildSpec() {
  const paths = buildPaths(routeModules);
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(paths).sort()) {
    sorted[key] = paths[key];
  }
  return {
    openapi: "3.0.3",
    info: {
      title: "MCT Client Portal API",
      description:
        "Maine CyberTech Client Portal API. Bearer token authentication required unless noted as public.",
      version: "1.0.0",
      contact: { name: "MCT Support", email: "support@mainecybertech.com" },
    },
    servers: [
      { url: "https://api.mainecybertech.com", description: "Production" },
      { url: "https://api.mainecybertech.us", description: "Dev" },
      { url: "http://localhost:4000", description: "Local development" },
    ],
    security: [{ bearerAuth: [] }],
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
      },
    },
    paths: sorted,
  };
}
