import { buildPaths, type RouteDef, pathParam, queryParam } from "./builder";

const auth: RouteDef[] = [
  { method: "post", path: "/auth/sign-in", summary: "Sign in with email/password", tag: "Auth", auth: false, body: { type: "object", properties: { email: { type: "string" }, password: { type: "string" } }, required: ["email", "password"] } },
  { method: "post", path: "/auth/sign-up", summary: "Create account", tag: "Auth", auth: false, body: { type: "object", properties: { email: { type: "string" }, password: { type: "string" }, fullName: { type: "string" } }, required: ["email", "password"] } },
  { method: "post", path: "/auth/sign-out", summary: "Sign out", tag: "Auth", auth: false },
  { method: "get", path: "/auth/me", summary: "Get current user", tag: "Auth" },
  { method: "post", path: "/auth/callback", summary: "Exchange auth code for session", tag: "Auth", auth: false },
  { method: "post", path: "/auth/forgot-password", summary: "Request password reset email", tag: "Auth", auth: false, body: { type: "object", properties: { email: { type: "string" } }, required: ["email"] } },
  { method: "post", path: "/auth/reset-password", summary: "Reset password with token", tag: "Auth", auth: false, body: { type: "object", properties: { token: { type: "string" }, password: { type: "string" } }, required: ["token", "password"] } },
];

const auth2: RouteDef[] = [
  { method: "get", path: "/profiles", summary: "List profiles", tag: "Profiles" },
  { method: "patch", path: "/profiles/{id}", summary: "Update profile", tag: "Profiles", params: [pathParam("id")] },
  { method: "post", path: "/profiles/{id}/avatar", summary: "Upload avatar", tag: "Profiles", params: [pathParam("id")] },
  { method: "get", path: "/organizations", summary: "List organizations", tag: "Organizations" },
  { method: "post", path: "/organizations", summary: "Create organization", tag: "Organizations" },
  { method: "get", path: "/organizations/{id}", summary: "Get organization", tag: "Organizations", params: [pathParam("id")] },
  { method: "patch", path: "/organizations/{id}", summary: "Update organization", tag: "Organizations", params: [pathParam("id")] },
  { method: "delete", path: "/organizations/{id}", summary: "Delete organization", tag: "Organizations", params: [pathParam("id")] },
  { method: "get", path: "/organizations/{id}/detail", summary: "Get organization detail (compound)", tag: "Organizations", params: [pathParam("id")] },
  { method: "post", path: "/organizations/{id}/logo", summary: "Upload organization logo", tag: "Organizations", params: [pathParam("id")] },
  { method: "get", path: "/organizations/{id}/domains", summary: "List organization domains", tag: "Organizations", params: [pathParam("id")] },
  { method: "post", path: "/organizations/{id}/domains", summary: "Add domain", tag: "Organizations", params: [pathParam("id")] },
  { method: "patch", path: "/organizations/{id}/domains/{domainId}", summary: "Verify domain", tag: "Organizations", params: [pathParam("id"), pathParam("domainId")] },
  { method: "delete", path: "/organizations/{id}/domains/{domainId}", summary: "Remove domain", tag: "Organizations", params: [pathParam("id"), pathParam("domainId")] },
  { method: "get", path: "/memberships", summary: "List memberships", tag: "Memberships" },
  { method: "get", path: "/memberships/mine", summary: "Get my memberships", tag: "Memberships" },
  { method: "post", path: "/memberships/invite", summary: "Invite user to org", tag: "Memberships" },
  { method: "patch", path: "/memberships/{id}", summary: "Update membership status", tag: "Memberships", params: [pathParam("id")] },
  { method: "delete", path: "/memberships/{id}", summary: "Remove membership", tag: "Memberships", params: [pathParam("id")] },
  { method: "get", path: "/users", summary: "List users", tag: "Users" },
  { method: "get", path: "/users/{id}", summary: "Get user", tag: "Users", params: [pathParam("id")] },
  { method: "get", path: "/users/{id}/detail", summary: "Get user with memberships (compound)", tag: "Users", params: [pathParam("id")] },
  { method: "patch", path: "/users/{id}/role", summary: "Update user role", tag: "Users", params: [pathParam("id")] },
  { method: "get", path: "/users/{id}/permissions", summary: "Get user permissions", tag: "Users", params: [pathParam("id")] },
  { method: "put", path: "/users/{id}/permissions", summary: "Update user permission overrides", tag: "Users", params: [pathParam("id")] },
  { method: "get", path: "/roles", summary: "List roles", tag: "Roles" },
  { method: "get", path: "/roles/with-permissions", summary: "List roles with permission counts", tag: "Roles" },
  { method: "post", path: "/roles", summary: "Create role", tag: "Roles" },
  { method: "get", path: "/roles/{id}", summary: "Get role", tag: "Roles", params: [pathParam("id")] },
  { method: "patch", path: "/roles/{id}", summary: "Update role", tag: "Roles", params: [pathParam("id")] },
  { method: "delete", path: "/roles/{id}", summary: "Delete role", tag: "Roles", params: [pathParam("id")] },
  { method: "get", path: "/roles/{id}/permissions", summary: "List role permissions", tag: "Roles", params: [pathParam("id")] },
  { method: "put", path: "/roles/{id}/permissions", summary: "Update role permissions", tag: "Roles", params: [pathParam("id")] },
];

const ticketsProjects: RouteDef[] = [
  { method: "get", path: "/tickets", summary: "List tickets", tag: "Tickets", params: [queryParam("status"), queryParam("priority"), queryParam("page"), queryParam("limit")] },
  { method: "post", path: "/tickets", summary: "Create ticket", tag: "Tickets" },
  { method: "post", path: "/tickets/bulk", summary: "Bulk update tickets", tag: "Tickets" },
  { method: "get", path: "/tickets/export", summary: "Export tickets (CSV/JSON)", tag: "Tickets", params: [queryParam("format"), queryParam("status")] },
  { method: "get", path: "/tickets/{id}", summary: "Get ticket", tag: "Tickets", params: [pathParam("id")] },
  { method: "patch", path: "/tickets/{id}", summary: "Update ticket", tag: "Tickets", params: [pathParam("id")] },
  { method: "delete", path: "/tickets/{id}", summary: "Delete ticket", tag: "Tickets", params: [pathParam("id")] },
  { method: "get", path: "/tickets/{id}/comments", summary: "List ticket comments", tag: "Tickets", params: [pathParam("id")] },
  { method: "post", path: "/tickets/{id}/comments", summary: "Add ticket comment", tag: "Tickets", params: [pathParam("id")] },
  { method: "patch", path: "/tickets/{id}/comments/{commentId}", summary: "Edit ticket comment", tag: "Tickets", params: [pathParam("id"), pathParam("commentId")] },
  { method: "get", path: "/projects", summary: "List projects", tag: "Projects", params: [queryParam("status"), queryParam("page"), queryParam("limit")] },
  { method: "post", path: "/projects", summary: "Create project", tag: "Projects" },
  { method: "get", path: "/projects/export", summary: "Export projects (CSV/JSON)", tag: "Projects", params: [queryParam("format")] },
  { method: "get", path: "/projects/{id}", summary: "Get project", tag: "Projects", params: [pathParam("id")] },
  { method: "patch", path: "/projects/{id}", summary: "Update project", tag: "Projects", params: [pathParam("id")] },
  { method: "delete", path: "/projects/{id}", summary: "Delete project", tag: "Projects", params: [pathParam("id")] },
  { method: "get", path: "/projects/{id}/detail", summary: "Get project detail (compound)", tag: "Projects", params: [pathParam("id")] },
  { method: "get", path: "/projects/{id}/tasks", summary: "List project tasks", tag: "Projects", params: [pathParam("id")] },
  { method: "post", path: "/projects/{id}/tasks", summary: "Create project task", tag: "Projects", params: [pathParam("id")] },
  { method: "patch", path: "/projects/{id}/tasks/{taskId}", summary: "Update task", tag: "Projects", params: [pathParam("id"), pathParam("taskId")] },
  { method: "delete", path: "/projects/{id}/tasks/{taskId}", summary: "Delete task", tag: "Projects", params: [pathParam("id"), pathParam("taskId")] },
  { method: "get", path: "/projects/{id}/tasks/{taskId}/comments", summary: "List task comments", tag: "Projects", params: [pathParam("id"), pathParam("taskId")] },
  { method: "post", path: "/projects/{id}/tasks/{taskId}/comments", summary: "Add task comment", tag: "Projects", params: [pathParam("id"), pathParam("taskId")] },
  { method: "patch", path: "/projects/{id}/tasks/{taskId}/comments/{commentId}", summary: "Edit task comment", tag: "Projects", params: [pathParam("id"), pathParam("taskId"), pathParam("commentId")] },
  { method: "get", path: "/projects/{id}/tasks/comments", summary: "List all task comments", tag: "Projects", params: [pathParam("id")] },
  { method: "get", path: "/projects/{id}/tasks/read-states", summary: "Get task read states", tag: "Projects", params: [pathParam("id")] },
  { method: "post", path: "/projects/{id}/tasks/reorder", summary: "Reorder tasks", tag: "Projects", params: [pathParam("id")] },
  { method: "post", path: "/projects/{id}/tasks/{taskId}/read", summary: "Mark task read", tag: "Projects", params: [pathParam("id"), pathParam("taskId")] },
  { method: "post", path: "/projects/{id}/tasks/{taskId}/approve", summary: "Approve task", tag: "Projects", params: [pathParam("id"), pathParam("taskId")] },
  { method: "post", path: "/projects/{id}/tasks/{taskId}/portal-comment", summary: "Add portal comment to task", tag: "Projects", params: [pathParam("id"), pathParam("taskId")] },
  { method: "get", path: "/projects/{id}/updates", summary: "List project updates", tag: "Projects", params: [pathParam("id")] },
  { method: "post", path: "/projects/{id}/updates", summary: "Create project update", tag: "Projects", params: [pathParam("id")] },
  { method: "patch", path: "/projects/{id}/updates/{updateId}", summary: "Update project update", tag: "Projects", params: [pathParam("id"), pathParam("updateId")] },
  { method: "delete", path: "/projects/{id}/updates/{updateId}", summary: "Delete project update", tag: "Projects", params: [pathParam("id"), pathParam("updateId")] },
  { method: "get", path: "/documents", summary: "List documents", tag: "Documents", params: [queryParam("type"), queryParam("page"), queryParam("limit")] },
  { method: "post", path: "/documents", summary: "Create document metadata", tag: "Documents" },
  { method: "post", path: "/documents/upload", summary: "Upload document file", tag: "Documents" },
  { method: "delete", path: "/documents/{id}", summary: "Delete document", tag: "Documents", params: [pathParam("id")] },
  { method: "patch", path: "/documents/{id}", summary: "Update document", tag: "Documents", params: [pathParam("id")] },
  { method: "get", path: "/documents/{id}/signed-url", summary: "Get signed download URL", tag: "Documents", params: [pathParam("id")] },
  { method: "get", path: "/documents/{id}/versions", summary: "List document versions", tag: "Documents", params: [pathParam("id")] },
  { method: "get", path: "/documents/{id}/versions/{versionId}", summary: "Get document version", tag: "Documents", params: [pathParam("id"), pathParam("versionId")] },
  { method: "post", path: "/documents/bulk/folder", summary: "Bulk folder move", tag: "Documents" },
  { method: "post", path: "/documents/bulk/metadata", summary: "Bulk metadata update", tag: "Documents" },
];

const billingNotifications: RouteDef[] = [
  { method: "get", path: "/billing/summary", summary: "Get billing summary", tag: "Billing" },
  { method: "get", path: "/billing/invoices", summary: "List invoices", tag: "Billing" },
  { method: "get", path: "/billing/invoices/{id}", summary: "Get invoice", tag: "Billing", params: [pathParam("id")] },
  { method: "get", path: "/billing/subscriptions", summary: "List subscriptions", tag: "Billing" },
  { method: "get", path: "/billing/payments", summary: "List payments", tag: "Billing" },
  { method: "post", path: "/billing/sync", summary: "Sync billing data from Stripe", tag: "Billing" },
  { method: "get", path: "/notifications", summary: "List notifications", tag: "Notifications", params: [queryParam("unread"), queryParam("page"), queryParam("limit")] },
  { method: "get", path: "/notifications/unread-count", summary: "Get unread count", tag: "Notifications" },
  { method: "get", path: "/notifications/stream", summary: "SSE stream for real-time notifications", tag: "Notifications" },
  { method: "post", path: "/notifications", summary: "Create notification (admin)", tag: "Notifications" },
  { method: "post", path: "/notifications/{id}/read", summary: "Mark notification read", tag: "Notifications", params: [pathParam("id")] },
  { method: "post", path: "/notifications/mark-all-read", summary: "Mark all notifications read", tag: "Notifications" },
  { method: "delete", path: "/notifications/{id}", summary: "Delete notification", tag: "Notifications", params: [pathParam("id")] },
  { method: "get", path: "/notification-preferences", summary: "Get notification preferences", tag: "Notifications" },
  { method: "put", path: "/notification-preferences", summary: "Update notification preferences", tag: "Notifications" },
];

const adminAudit: RouteDef[] = [
  { method: "get", path: "/admin/dashboard", summary: "Admin dashboard data", tag: "Admin" },
  { method: "get", path: "/audit", summary: "List audit logs", tag: "Audit", params: [queryParam("entity_type"), queryParam("action"), queryParam("page"), queryParam("limit")] },
  { method: "get", path: "/audit/export", summary: "Export audit logs (CSV/JSON)", tag: "Audit", params: [queryParam("format")] },
  { method: "get", path: "/search", summary: "Admin global search", tag: "Search", params: [queryParam("q")] },
  { method: "get", path: "/search/portal", summary: "Portal-scoped search", tag: "Search", params: [queryParam("q")] },
  { method: "get", path: "/admin/health", summary: "Health dashboard data", tag: "Admin" },
  { method: "get", path: "/sla", summary: "List SLA metrics", tag: "Admin" },
  { method: "get", path: "/api-keys", summary: "List API keys", tag: "Admin" },
  { method: "post", path: "/api-keys", summary: "Create API key", tag: "Admin" },
  { method: "patch", path: "/api-keys/{id}", summary: "Update API key", tag: "Admin", params: [pathParam("id")] },
  { method: "delete", path: "/api-keys/{id}", summary: "Delete API key", tag: "Admin", params: [pathParam("id")] },
];

const systemWebhooks: RouteDef[] = [
  { method: "post", path: "/webhooks/stripe", summary: "Stripe webhook handler", tag: "Webhooks", auth: false },
  { method: "post", path: "/webhooks/jira", summary: "Jira webhook handler", tag: "Webhooks", auth: false },
  { method: "post", path: "/webhooks/jsm", summary: "JSM webhook handler", tag: "Webhooks", auth: false },
  { method: "post", path: "/webhooks/m365", summary: "M365 webhook handler", tag: "Webhooks", auth: false },
  { method: "get", path: "/webhook-endpoints", summary: "List webhook endpoints", tag: "Webhooks" },
  { method: "post", path: "/webhook-endpoints", summary: "Create webhook endpoint", tag: "Webhooks" },
  { method: "get", path: "/webhook-endpoints/{id}", summary: "Get webhook endpoint", tag: "Webhooks", params: [pathParam("id")] },
  { method: "patch", path: "/webhook-endpoints/{id}", summary: "Update webhook endpoint", tag: "Webhooks", params: [pathParam("id")] },
  { method: "delete", path: "/webhook-endpoints/{id}", summary: "Delete webhook endpoint", tag: "Webhooks", params: [pathParam("id")] },
  { method: "get", path: "/webhook-endpoints/{id}/deliveries", summary: "List webhook deliveries", tag: "Webhooks", params: [pathParam("id")] },
  { method: "post", path: "/webhook-endpoints/{id}/test", summary: "Test webhook endpoint", tag: "Webhooks", params: [pathParam("id")] },
  { method: "post", path: "/bulk/invite", summary: "Bulk invite users (CSV)", tag: "Admin" },
  { method: "post", path: "/public/init", summary: "Public init (CSRF token)", tag: "Public", auth: false },
  { method: "post", path: "/public/submit", summary: "Public form submission", tag: "Public", auth: false },
];

const businessModules: RouteDef[] = [
  { method: "post", path: "/store/promotions", summary: "Create promotion", tag: "Store" },
  { method: "get", path: "/store/promotions", summary: "List promotions", tag: "Store" },
  { method: "get", path: "/store/promotions/active", summary: "List active promotions (public)", tag: "Store", auth: false },
  { method: "patch", path: "/store/promotions/{id}", summary: "Update promotion", tag: "Store", params: [pathParam("id")] },
  { method: "delete", path: "/store/promotions/{id}", summary: "Delete promotion", tag: "Store", params: [pathParam("id")] },
  { method: "post", path: "/store/quotes", summary: "Submit quote request", tag: "Store", auth: false },
  { method: "get", path: "/store/quotes", summary: "List quote requests (admin)", tag: "Store" },
  { method: "get", path: "/store/quotes/{id}", summary: "Get quote request", tag: "Store", params: [pathParam("id")] },
  { method: "get", path: "/store/products", summary: "List products (public)", tag: "Store", auth: false, params: [queryParam("category")] },
  { method: "get", path: "/store/products/{slug}", summary: "Get product by slug (public)", tag: "Store", auth: false, params: [pathParam("slug")] },
  { method: "get", path: "/store/categories", summary: "List categories (public)", tag: "Store", auth: false },
  { method: "get", path: "/store/categories/{slug}", summary: "Get category with products (public)", tag: "Store", auth: false, params: [pathParam("slug")] },
  { method: "post", path: "/analytics/track", summary: "Track analytics event (public)", tag: "Analytics", auth: false },
  { method: "get", path: "/analytics", summary: "List analytics events (admin)", tag: "Analytics" },
  { method: "get", path: "/proposals", summary: "List proposals", tag: "Proposals" },
  { method: "post", path: "/proposals", summary: "Create proposal", tag: "Proposals" },
  { method: "get", path: "/proposals/{id}", summary: "Get proposal", tag: "Proposals", params: [pathParam("id")] },
  { method: "patch", path: "/proposals/{id}", summary: "Update proposal", tag: "Proposals", params: [pathParam("id")] },
  { method: "delete", path: "/proposals/{id}", summary: "Delete proposal", tag: "Proposals", params: [pathParam("id")] },
  { method: "get", path: "/findings", summary: "List findings", tag: "Findings" },
  { method: "get", path: "/findings/export", summary: "Export findings (CSV/JSON)", tag: "Findings", params: [queryParam("format")] },
  { method: "post", path: "/findings", summary: "Create finding", tag: "Findings" },
  { method: "get", path: "/findings/{id}", summary: "Get finding", tag: "Findings", params: [pathParam("id")] },
  { method: "patch", path: "/findings/{id}", summary: "Update finding", tag: "Findings", params: [pathParam("id")] },
  { method: "delete", path: "/findings/{id}", summary: "Delete finding", tag: "Findings", params: [pathParam("id")] },
  { method: "get", path: "/governance/policies", summary: "List policies", tag: "Governance" },
  { method: "post", path: "/governance/policies", summary: "Create policy", tag: "Governance" },
  { method: "get", path: "/governance/policies/{id}", summary: "Get policy", tag: "Governance", params: [pathParam("id")] },
  { method: "patch", path: "/governance/policies/{id}", summary: "Update policy", tag: "Governance", params: [pathParam("id")] },
  { method: "delete", path: "/governance/policies/{id}", summary: "Delete policy", tag: "Governance", params: [pathParam("id")] },
  { method: "get", path: "/governance/controls", summary: "List controls", tag: "Governance" },
  { method: "get", path: "/governance/controls/{id}", summary: "Get control", tag: "Governance", params: [pathParam("id")] },
  { method: "get", path: "/governance/risks", summary: "List risks", tag: "Governance" },
  { method: "post", path: "/governance/risks", summary: "Create risk", tag: "Governance" },
  { method: "post", path: "/governance/risks/{id}/assess", summary: "Assess risk", tag: "Governance", params: [pathParam("id")] },
  { method: "get", path: "/service-catalog", summary: "List service catalog", tag: "ServiceCatalog" },
  { method: "get", path: "/service-catalog/{id}", summary: "Get service catalog item", tag: "ServiceCatalog", params: [pathParam("id")] },
  { method: "post", path: "/business-os", summary: "Get business OS summary", tag: "BusinessOS" },
  { method: "get", path: "/assets", summary: "List assets", tag: "Assets" },
  { method: "get", path: "/assets/stats", summary: "Asset statistics", tag: "Assets" },
  { method: "get", path: "/assets/export", summary: "Export assets (CSV/JSON)", tag: "Assets", params: [queryParam("format")] },
  { method: "post", path: "/assets", summary: "Create asset", tag: "Assets" },
  { method: "get", path: "/assets/{id}", summary: "Get asset", tag: "Assets", params: [pathParam("id")] },
  { method: "patch", path: "/assets/{id}", summary: "Update asset", tag: "Assets", params: [pathParam("id")] },
  { method: "delete", path: "/assets/{id}", summary: "Delete asset", tag: "Assets", params: [pathParam("id")] },
  { method: "post", path: "/assets/{id}/comments", summary: "Add asset comment", tag: "Assets", params: [pathParam("id")] },
  { method: "get", path: "/domain-monitors", summary: "List domain monitors", tag: "DomainMonitors" },
  { method: "get", path: "/domain-monitors/stats", summary: "Domain monitor statistics", tag: "DomainMonitors" },
  { method: "get", path: "/domain-monitors/export", summary: "Export domain monitors", tag: "DomainMonitors", params: [queryParam("format")] },
  { method: "post", path: "/domain-monitors", summary: "Create domain monitor", tag: "DomainMonitors" },
  { method: "get", path: "/domain-monitors/{id}", summary: "Get domain monitor", tag: "DomainMonitors", params: [pathParam("id")] },
  { method: "patch", path: "/domain-monitors/{id}", summary: "Update domain monitor", tag: "DomainMonitors", params: [pathParam("id")] },
  { method: "delete", path: "/domain-monitors/{id}", summary: "Delete domain monitor", tag: "DomainMonitors", params: [pathParam("id")] },
  { method: "post", path: "/domain-monitors/{id}/scan", summary: "Trigger domain scan", tag: "DomainMonitors", params: [pathParam("id")] },
  { method: "get", path: "/security-suite", summary: "Security suite summary", tag: "SecuritySuite" },
  { method: "post", path: "/security-suite/m365-hardening/{id}/scan", summary: "Run M365 hardening scan", tag: "SecuritySuite", params: [pathParam("id")] },
  { method: "get", path: "/security-ops", summary: "Security ops summary", tag: "SecurityOps" },
  { method: "get", path: "/field-services", summary: "Field services summary", tag: "FieldServices" },
  { method: "get", path: "/edu-automation", summary: "Education automation summary", tag: "EduAutomation" },
  { method: "get", path: "/file-requests", summary: "List file requests", tag: "FileRequests" },
  { method: "post", path: "/file-requests", summary: "Create file request", tag: "FileRequests" },
  { method: "get", path: "/file-requests/{id}", summary: "Get file request", tag: "FileRequests", params: [pathParam("id")] },
  { method: "post", path: "/file-requests/{id}/upload", summary: "Upload to file request", tag: "FileRequests", params: [pathParam("id")] },
  { method: "get", path: "/approvals", summary: "List approvals", tag: "Approvals" },
  { method: "get", path: "/approvals/export", summary: "Export approvals (CSV/JSON)", tag: "Approvals", params: [queryParam("format")] },
  { method: "post", path: "/approvals", summary: "Create approval request", tag: "Approvals" },
  { method: "get", path: "/approvals/{id}", summary: "Get approval", tag: "Approvals", params: [pathParam("id")] },
  { method: "patch", path: "/approvals/{id}", summary: "Update approval", tag: "Approvals", params: [pathParam("id")] },
  { method: "post", path: "/approvals/{id}/approve", summary: "Approve/reject", tag: "Approvals", params: [pathParam("id")] },
  { method: "get", path: "/vendors", summary: "List vendors", tag: "Vendors" },
  { method: "get", path: "/vendors/export", summary: "Export vendors", tag: "Vendors", params: [queryParam("format")] },
  { method: "post", path: "/vendors", summary: "Create vendor", tag: "Vendors" },
  { method: "get", path: "/vendors/{id}", summary: "Get vendor", tag: "Vendors", params: [pathParam("id")] },
  { method: "patch", path: "/vendors/{id}", summary: "Update vendor", tag: "Vendors", params: [pathParam("id")] },
  { method: "delete", path: "/vendors/{id}", summary: "Delete vendor", tag: "Vendors", params: [pathParam("id")] },
  { method: "get", path: "/vendors/{id}/contracts", summary: "List vendor contracts", tag: "Vendors", params: [pathParam("id")] },
  { method: "post", path: "/vendors/{id}/contracts", summary: "Add vendor contract", tag: "Vendors", params: [pathParam("id")] },
  { method: "get", path: "/vendors/{id}/contacts", summary: "List vendor contacts", tag: "Vendors", params: [pathParam("id")] },
  { method: "post", path: "/vendors/{id}/contacts", summary: "Add vendor contact", tag: "Vendors", params: [pathParam("id")] },
  { method: "get", path: "/qbr", summary: "List QBR reports", tag: "QBR" },
  { method: "post", path: "/qbr", summary: "Create QBR report", tag: "QBR" },
  { method: "get", path: "/qbr/{id}", summary: "Get QBR report", tag: "QBR", params: [pathParam("id")] },
  { method: "patch", path: "/qbr/{id}", summary: "Update QBR report", tag: "QBR", params: [pathParam("id")] },
  { method: "delete", path: "/qbr/{id}", summary: "Delete QBR report", tag: "QBR", params: [pathParam("id")] },
  { method: "get", path: "/dmarc-coach", summary: "List DMARC assessments", tag: "DMARCCoach" },
  { method: "post", path: "/dmarc-coach/scan/{id}", summary: "Run DMARC scan", tag: "DMARCCoach", params: [pathParam("id")] },
  { method: "get", path: "/uptime-monitor", summary: "List uptime monitors", tag: "UptimeMonitor" },
  { method: "post", path: "/uptime-monitor/{id}/check", summary: "Run uptime check", tag: "UptimeMonitor", params: [pathParam("id")] },
  { method: "get", path: "/status-page", summary: "List status pages", tag: "StatusPage" },
  { method: "get", path: "/training-hub", summary: "List training modules", tag: "TrainingHub" },
  { method: "get", path: "/license-optimizer", summary: "License optimizer summary", tag: "LicenseOptimizer" },
  { method: "get", path: "/ai", summary: "List AI tools", tag: "AI" },
  { method: "post", path: "/ai/{id}/generate", summary: "Generate AI content", tag: "AI", params: [pathParam("id")] },
  { method: "get", path: "/batch", summary: "List batch operations", tag: "Batch" },
  { method: "post", path: "/batch", summary: "Submit batch operation", tag: "Batch" },
  { method: "get", path: "/sop-library", summary: "List SOPs", tag: "SOP" },
  { method: "get", path: "/sop-library/{id}", summary: "Get SOP", tag: "SOP", params: [pathParam("id")] },
  { method: "get", path: "/final", summary: "List final assessments", tag: "Final" },
  { method: "post", path: "/final", summary: "Create final assessment", tag: "Final" },
  { method: "get", path: "/client-onboarding", summary: "Client onboarding status", tag: "Onboarding" },
  { method: "get", path: "/satisfaction-pulse", summary: "Satisfaction pulse surveys", tag: "Satisfaction" },
  { method: "get", path: "/dynamic-forms", summary: "Dynamic forms", tag: "Forms" },
  { method: "get", path: "/insurance-binder", summary: "Insurance binder", tag: "Insurance" },
  { method: "get", path: "/dashboard/summary", summary: "Dashboard summary", tag: "Dashboard" },
  { method: "get", path: "/dashboard/activity-feed", summary: "Recent activity feed", tag: "Dashboard" },
];

export const routeModules: RouteDef[] = [
  ...auth,
  ...auth2,
  ...ticketsProjects,
  ...billingNotifications,
  ...adminAudit,
  ...systemWebhooks,
  ...businessModules,
];

export function buildSpec() {
  const paths = buildPaths(routeModules);
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(paths).sort()) {
    sorted[key] = paths[key];
  }
  return {
    openapi: "3.0.3",
    info: {
      title: "MCT Client Portal API",
      description: "Maine CyberTech Client Portal API. Bearer token authentication required unless noted as public.",
      version: "1.0.0",
      contact: { name: "MCT Support", email: "support@mainecybertech.com" },
    },
    servers: [
      { url: "https://api.mainecybertech.com", description: "Production" },
      { url: "https://api.mainecybertech.us", description: "Dev" },
      { url: "http://localhost:4000", description: "Local development" },
    ],
    security: [{ bearerAuth: [] }],
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
      },
    },
    paths: sorted,
  };
}
