-- Add missing DELETE RLS policies to all batch migration tables
-- This is defense-in-depth: API uses service_role which bypasses RLS,
-- but if client mode ever changes, these guards protect org-scoped data.

-- 5302068: batch_modules (license_tracking, status_items, website_monitors, dmarc_assessments)
create policy "license_tracking_delete_admin" on license_tracking for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = license_tracking.organization_id and r.key in ('super_admin', 'admin')));
create policy "status_items_delete_admin" on status_items for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = status_items.organization_id and r.key in ('super_admin', 'admin')));
create policy "website_monitors_delete_admin" on website_monitors for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = website_monitors.organization_id and r.key in ('super_admin', 'admin')));
create policy "dmarc_assessments_delete_admin" on dmarc_assessments for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = dmarc_assessments.organization_id and r.key in ('super_admin', 'admin')));

-- 5302069: security_ops (offboarding_checklists, break_glass_accounts, onboarding_clients, patch_compliance)
create policy "offboarding_delete_admin" on offboarding_checklists for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = offboarding_checklists.organization_id and r.key in ('super_admin', 'admin')));
create policy "break_glass_delete_admin" on break_glass_accounts for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = break_glass_accounts.organization_id and r.key in ('super_admin', 'admin')));
create policy "onboarding_delete_admin" on onboarding_clients for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = onboarding_clients.organization_id and r.key in ('super_admin', 'admin')));
create policy "patch_compliance_delete_admin" on patch_compliance for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = patch_compliance.organization_id and r.key in ('super_admin', 'admin')));

-- 5302070: security_suite (m365_hardening, incident_responses, identity_verifications, endpoint_security)
create policy "m365_delete_admin" on m365_hardening for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = m365_hardening.organization_id and r.key in ('super_admin', 'admin')));
create policy "incident_delete_admin" on incident_responses for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = incident_responses.organization_id and r.key in ('super_admin', 'admin')));
create policy "idverify_delete_admin" on identity_verifications for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = identity_verifications.organization_id and r.key in ('super_admin', 'admin')));
create policy "ep_delete_admin" on endpoint_security for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = endpoint_security.organization_id and r.key in ('super_admin', 'admin')));

-- 5302071: governance (change_requests, risk_register, retention_policies, tabletop_exercises)
create policy "cr_delete_admin" on change_requests for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = change_requests.organization_id and r.key in ('super_admin', 'admin')));
create policy "risk_delete_admin" on risk_register for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = risk_register.organization_id and r.key in ('super_admin', 'admin')));
create policy "retention_delete_admin" on retention_policies for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = retention_policies.organization_id and r.key in ('super_admin', 'admin')));
create policy "tt_delete_admin" on tabletop_exercises for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = tabletop_exercises.organization_id and r.key in ('super_admin', 'admin')));

-- 5302072: field_services (isp_assessments, unifi_surveys, port_maps, camera_calculations, hardware_staging, network_diagrams)
create policy "isp_delete_admin" on isp_assessments for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = isp_assessments.organization_id and r.key in ('super_admin', 'admin')));
create policy "us_delete_admin" on unifi_surveys for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = unifi_surveys.organization_id and r.key in ('super_admin', 'admin')));
create policy "pm_delete_admin" on port_maps for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = port_maps.organization_id and r.key in ('super_admin', 'admin')));
create policy "cc_delete_admin" on camera_calculations for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = camera_calculations.organization_id and r.key in ('super_admin', 'admin')));
create policy "hs_delete_admin" on hardware_staging for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = hardware_staging.organization_id and r.key in ('super_admin', 'admin')));
create policy "nd_delete_admin" on network_diagrams for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = network_diagrams.organization_id and r.key in ('super_admin', 'admin')));

-- 5302073: edu_automation (11 tables)
create policy "sop_delete_admin" on sop_library for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = sop_library.organization_id and r.key in ('super_admin', 'admin')));
create policy "compliance_delete_admin" on compliance_readiness for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = compliance_readiness.organization_id and r.key in ('super_admin', 'admin')));
create policy "ie_delete_admin" on insurance_evidence for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = insurance_evidence.organization_id and r.key in ('super_admin', 'admin')));
create policy "ap_delete_admin" on ai_policies for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = ai_policies.organization_id and r.key in ('super_admin', 'admin')));
create policy "kb_delete_admin" on knowledge_articles for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = knowledge_articles.organization_id and r.key in ('super_admin', 'admin')));
create policy "tm_delete_admin" on training_modules for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = training_modules.organization_id and r.key in ('super_admin', 'admin')));
create policy "ph_delete_admin" on phishing_campaigns for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = phishing_campaigns.organization_id and r.key in ('super_admin', 'admin')));
create policy "cs_delete_admin" on cyber_scorecards for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = cyber_scorecards.organization_id and r.key in ('super_admin', 'admin')));
create policy "aw_delete_admin" on automation_workflows for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = automation_workflows.organization_id and r.key in ('super_admin', 'admin')));
create policy "ps_delete_admin" on powershell_scripts for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = powershell_scripts.organization_id and r.key in ('super_admin', 'admin')));
create policy "kbg_delete_admin" on kb_article_generations for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = kb_article_generations.organization_id and r.key in ('super_admin', 'admin')));

-- 5302074: final_batch (10 tables)
create policy "sp_delete_admin" on sharepoint_plans for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = sharepoint_plans.organization_id and r.key in ('super_admin', 'admin')));
create policy "dp_delete_admin" on device_profiles for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = device_profiles.organization_id and r.key in ('super_admin', 'admin')));
create policy "sa_delete_admin" on saas_audits for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = saas_audits.organization_id and r.key in ('super_admin', 'admin')));
create policy "pq_delete_admin" on procurement_quotes for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = procurement_quotes.organization_id and r.key in ('super_admin', 'admin')));
create policy "dns_delete_admin" on dns_change_requests for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = dns_change_requests.organization_id and r.key in ('super_admin', 'admin')));
create policy "sp2_delete_admin" on satisfaction_pulses for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = satisfaction_pulses.organization_id and r.key in ('super_admin', 'admin')));
create policy "te_delete_admin" on time_entries for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = time_entries.organization_id and r.key in ('super_admin', 'admin')));
create policy "br_delete_admin" on budget_roadmaps for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = budget_roadmaps.organization_id and r.key in ('super_admin', 'admin')));
create policy "crb_delete_admin" on client_runbooks for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = client_runbooks.organization_id and r.key in ('super_admin', 'admin')));
create policy "cf_delete_admin" on custom_forms for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = custom_forms.organization_id and r.key in ('super_admin', 'admin')));

-- 5302075: backup_dr (backup_status)
create policy "backup_delete_admin" on backup_status for delete using (exists (select 1 from memberships m join roles r on m.role_id = r.id where m.user_id = auth.uid() and m.organization_id = backup_status.organization_id and r.key in ('super_admin', 'admin')));
