-- Remaining: SharePoint (#54) + Device Profiles (#46) + SaaS Audit (#8) + Procurement (#44) + DNS Changes (#55) + Satisfaction (#38) + Time Entry (#57) + Budget (#35) + Runbook (#32) + Forms (#42)
begin;

create table if not exists sharepoint_plans (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, site_name text not null, team_name text, structure_type text default 'team_site', owner text, sensitivity_label text, external_sharing text default 'disabled', notes text, status text not null default 'planned', created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_sp_org on sharepoint_plans(organization_id);
alter table sharepoint_plans enable row level security; create policy "sp_org" on sharepoint_plans for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "sp_org_i" on sharepoint_plans for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "sp_org_u" on sharepoint_plans for update using (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists device_profiles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, profile_name text not null, device_type text, os text, settings jsonb not null default '{}'::jsonb, description text, status text not null default 'active', created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_dp_org on device_profiles(organization_id);
alter table device_profiles enable row level security; create policy "dp_org" on device_profiles for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "dp_org_i" on device_profiles for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "dp_org_u" on device_profiles for update using (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists saas_audits (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, vendor_name text not null, service_name text not null, monthly_cost numeric(12,2), annual_cost numeric(12,2), payment_method text, classification text default 'unknown', usage_frequency text, cancellation_risk text, has_data_access boolean default false, renewal_date date, notes text, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_saas_org on saas_audits(organization_id);
alter table saas_audits enable row level security; create policy "sa_org" on saas_audits for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "sa_org_i" on saas_audits for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "sa_org_u" on saas_audits for update using (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists procurement_quotes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, vendor_name text not null, product text not null, quote_amount numeric(12,2), competitor_quote numeric(12,2), comparison_notes text, selected boolean default false, purchased_at timestamptz, notes text, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_pq_org on procurement_quotes(organization_id);
alter table procurement_quotes enable row level security; create policy "pq_org" on procurement_quotes for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "pq_org_i" on procurement_quotes for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "pq_org_u" on procurement_quotes for update using (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists dns_change_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, domain text not null, change_type text not null, change_description text, proposed_value text, current_value text, status text not null default 'pending', approved_by uuid references auth.users(id), implemented_at timestamptz, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_dns_org on dns_change_requests(organization_id);
alter table dns_change_requests enable row level security; create policy "dns_org" on dns_change_requests for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "dns_org_i" on dns_change_requests for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "dns_org_u" on dns_change_requests for update using (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists satisfaction_pulses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, subject text not null, question text, rating integer default 5, feedback text, source text default 'ticket', source_entity_id uuid, sent_at timestamptz, responded_at timestamptz, created_at timestamptz not null default now());
create index if not exists idx_sp_org2 on satisfaction_pulses(organization_id);
alter table satisfaction_pulses enable row level security; create policy "sp2_org" on satisfaction_pulses for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "sp2_org_i" on satisfaction_pulses for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists time_entries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, description text not null, hours numeric(5,2) default 0, billable boolean default true, work_date date, ticket_id uuid references tickets(id), user_id uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_te_org on time_entries(organization_id);
alter table time_entries enable row level security; create policy "te_org" on time_entries for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "te_org_i" on time_entries for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists budget_roadmaps (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, item_name text not null, category text default 'hardware', estimated_cost numeric(12,2), fiscal_year integer, quarter integer, priority text default 'medium', status text not null default 'planned', notes text, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_br_org on budget_roadmaps(organization_id);
alter table budget_roadmaps enable row level security; create policy "br_org" on budget_roadmaps for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "br_org_i" on budget_roadmaps for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "br_org_u" on budget_roadmaps for update using (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists client_runbooks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, title text not null, content text, category text, version text default '1.0', status text not null default 'draft', last_reviewed_at timestamptz, next_review_at timestamptz, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_crb_org on client_runbooks(organization_id);
alter table client_runbooks enable row level security; create policy "crb_org" on client_runbooks for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "crb_org_i" on client_runbooks for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "crb_org_u" on client_runbooks for update using (organization_id in (select organization_id from memberships where user_id = auth.uid()));

create table if not exists custom_forms (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, form_name text not null, form_description text, form_fields jsonb not null default '[]'::jsonb, is_active boolean default true, submission_count integer default 0, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_cf_org on custom_forms(organization_id);
alter table custom_forms enable row level security; create policy "cf_org" on custom_forms for select using (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "cf_org_i" on custom_forms for insert with check (organization_id in (select organization_id from memberships where user_id = auth.uid())); create policy "cf_org_u" on custom_forms for update using (organization_id in (select organization_id from memberships where user_id = auth.uid()));

commit;
