name: test-ssh-no-version
on:
  push:
    branches: [develop]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action
        with:
          host: example.com
          username: root
          key: ${{ secrets.CI_SSH_PRIVATE_KEY }}
          command_timeout: 45m
        script: echo hello
