name: test-reusable
on:
  push:
    branches: [develop]
jobs:
  validate:
    needs: []
    uses: ./.github/workflows/validate.yml
  test:
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
