name: test-ssh-action
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: example.com
          username: root
          key: ${{ secrets.CI_SSH_PRIVATE_KEY }}
          command_timeout: 45m
          envs: CF_ORIGIN_CERT,CF_ORIGIN_KEY,REDIS_PASSWORD
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          CF_ORIGIN_CERT: ${{ secrets.CF_ORIGIN_CERT }}
          CF_ORIGIN_KEY: ${{ secrets.CF_ORIGIN_KEY }}
        script: echo hello
