name: test-if-env
on:
  push:
    branches: [develop]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.env.outputs.name }}
    steps:
      - run: echo "name=dev" >> $GITHUB_OUTPUT
  deploy:
    needs: [setup]
    if: ${{ always() && !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.name }}
    steps:
      - run: echo hello
